### ISSUE TITLE
Repeatable AfterStage/BeforeStage methods

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#102]
BeforeStage and AfterStage methods are exactly executed once. This is sometimes not desirable if you want to use the same stage multiple times in the same scenario. For example, if you have a builder in the AfterStage method and you want it to built something each time the stage has finished. Thus it would be helpful to have a way of overriding this default behavior.

Idea: Give the `@AfterStage` annotation a new attribute `repeatable` that is by default `false`, but can be overridden:

```
@AfterStage( repeatable = true )
```

**Comment by nnar1o** [comment]
What about this feature? It would be useful in our project, too.

**Comment by l-1squared** [comment]
Hi @nnar1o,
this idea is quite old, and janschaefer has since left the project. Thus, it sat here unrecognized until you asked about it. However, after a brief look into the issue, it does not seem to be the worst idea, unfortunately it isn't a no-brainer either.
So, before I continue implementing this feature, may I ask you if it would be possible to provide a few (anonymized) scenarios, to understand the use case even better.

**Comment by l-1squared** [comment]
As an aside @nnar1o, do you feel confident to maybe hand in a contribution?

**Comment by l-1squared** [comment]
added spec for after stage feature in branch feature/repeatable-after-stage

**Comment by nnar1o** [comment]
Than you for response.

I will prepare a sample test to show the problem on an example.

I just wonder -Is the project going to be continued if Jan left? How many contributors are there currently? I just don't want to start to use it in my projest, write tests and have no support in the future - so maybe I will need to find some alternative.

**Comment by l-1squared** [comment]
While the implementation of repeatable methods is almost complete, it will at first not support the usage of the same class in consecutive stages. This affects, for instance SimpleScenarioTests, where one stage class acts as the given, when, and then stage.

The reason for not supporting them right now is that JGiven uses the change of a stage class to determine that, well, a new stage has been entered and it is now time to execute the stage lifecyle methods.

To allow the use of repeatable Stage Methods, the inner workings of JGiven would have to be refactored extensively.

**Comment by l-1squared** [comment]
@nnar1o  unfortunately I did not read your response properly until I came back here to add my progress to the issue. 
Of course the project is going to be continued. By me :), and @fudler  who helps me maintain it. The Project is also backed by [TNG Technology Consulting](https://tngtech.com/).
