### ISSUE TITLE
Question/Improvement: Custom StringConverter?

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#109]
Hi there,
a small question/improvement suggestion: it should be possible to override com.tngtech.java.junit.dataprovider.internal.convert.StringConverter, to be more precise the private Object convertValue(String str, Class<?> targetType) method. The background is to be able to support more parameter types in the @DataProvider annotation, e.g. Date and DateTime or any other types that don't have a constructor with string parameter.

Currently, the best option is to replace the StringConverter manually, but I'm sure this could be done better.

Best regards, Niko

**Comment by janschaefer** [comment]
Hi Niko,
the dataprovider is actually no part of JGiven, but a separate project. Please raise your question here: https://github.com/TNG/junit-dataprovider
