### ISSUE TITLE
a JSON report is generated only for one JGiven Test Scenario

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#115]
Given multiple JGiven Test Scenario classes based on TestNG
When running tests using Maven Surefire
Then a JSON report is generated only for one JGiven Test Scenario

As side note, same happens when I am running the tests programmatically like this:

    final TestNG testng = new TestNG();
    testng.setTestClasses(new Class[] { testClass1, testClass2, ... });
    testng.addListener(new TestListenerAdapter());
    testng.run();

**Comment by janschaefer** [comment]
Yes, admittedly, TestNG is not as well tested as JUnit. The defect will be fixed with the fix of #105

**Comment by janschaefer** [comment]
Thanks for your feedback btw!
