### ISSUE TITLE
HTML5 Report : allow certain attachments to be directly seen inside a scenario

### ISSUE THREAD

**Issue by mthuret** [TNG/JGiven#117]
Currently, when using attachments it add a link to see it. It's great when using this feature to see errors when tests are instrumented directly from a gui.

But it could also be use to add some diagrams to enrich the living documentation, and in that case it would be nice if pictures will be directly displayed beside the scenario itself.

What do you think  ?

**Comment by janschaefer** [comment]
That is actually a great idea! Also it should not be too hard to implement this.

**Comment by janschaefer** [comment]
This is now implemented with b05c6514e905f9ff106a488b3a81e82a1353d44d
