### ISSUE TITLE
@AfterStage called after JUnit @After

### ISSUE THREAD

**Issue by camproto** [TNG/JGiven#1247]
Using JUnit 4.13.2 and JGiven 0.18.2. 

Identified, that a method marked with @AfterStage is called AFTER method marked with @After. In my case this leads to a resource leak, because I released my resource in the JUnit @After method. 

In general, what is the relation of the JGiven lifecycle (as explained in the docs) with JUnit lifecyle? 
Miss this in your docs.

**Comment by l-1squared** [comment]
Hi @camproto,

for JUnit 4 we hook into the lifecycle as a Rule. JUnit 4 ordering is such that `@Before` and `@After` methods within a class will be executed closer to the actual test method, than any Rule. The ordering is therefore ruleBefore-> annotatedBefore -> test -> annotatedAfter -> ruleBefore.
