### ISSUE TITLE
Currency unit $ is not reporting correctly in @As description

### ISSUE THREAD

**Issue by manoj-fd** [TNG/JGiven#1253]
Issue:  As part of my test case, I am expected to use currency unit $ in my test description, however it's not working as expected.

Example -

@As("I have $$ 10") is returned as  `$ I have 10`, 

but the expectation is to return as `I have $ 10` as per jGiven documentation https://jgiven.org/userguide/#_parameters_within_a_sentence

![image](https://user-images.githubusercontent.com/100688166/230929973-7b5c1865-9209-4f80-ac8a-fe129db1af0f.png)

**Comment by l-1squared** [comment]
I reproduced the issue. However I will still require some time to fix it. Among other things, I found out that we indeed have to methods to format descriptions (one for @As and one for @CaseAs) both of which have issues.

**Comment by l-1squared** [comment]
I found a solution to the issue. As of now, $$ is treated as a single `$` character and will be considered part of a word.  

I am, however, not yet content with the implementation of the parser (first off, we have two), so I will need more time to iron this out.
