### ISSUE TITLE
Ability to define default formatters

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#126]
Hi Jan,

in my tests, I'm using various objects (e.g. enum uses a lowercase/replace _ with blank formatter, class uses a simple name formatter) where I supply the same formatter over and over again. Do you think it makes sense to be able to define a custom default formatter per class?

Best regards,
Niko

**Comment by janschaefer** [comment]
Yes, I already thought about this, see #113 ;-)

**Comment by nikowitt** [comment]
Arrrgh, I should have searched for "formatters", not for "default formatters" :(
