### ISSUE TITLE
Why is 'type' the scenario state fields default resolution?

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#127]
Hi Jan,

one question:
```
Scenario state fields are by default resolved by its type
```
To me, resolution by name is a more intuitive default approach. May I ask why you decided to use type resolution as default?

Regards.
Niko

**Comment by janschaefer** [comment]
It is the default that is typically used by injection frameworks like Spring or CDI, for example. I am also not that happy now about my own decision. However, it is now difficult to change that default behavior. One might think about a global configuration option to change that though.

**Comment by nikowitt** [comment]
Okay, thanks for letting me now. In our testing environment, I've built default stages that provide common methods that are required for our applications. I will just set all default fields to name resolution, so other developers have to care less about annotations on fields they need in specific cases.
