### ISSUE TITLE
Parameters are formatted as "arg0" in HTML Report using Java 7

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#128]
Hi Jan,

on our build servers, we use Debian with
```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode) 
```

The parameters in the generated HTML report are formatted as arg0, arg1 etc - I thought that this is only a Java 8 issue with an old paranamer lib? Do you know what to do with Java 7? The "-parameters" flag does not exist/work here.

Thanks!
Best regards,
Niko

**Comment by janschaefer** [comment]
This is actually strange. Which version of JGiven are you currently using?

**Comment by nikowitt** [comment]
The latest one, 0.8.3, we've just updated this morning.

**Comment by janschaefer** [comment]
It actually might be the case when you compile your test classes without debugging information. e.g. `javac -g:none`

**Comment by janschaefer** [comment]
Ok, maybe -g:vars is missing. I think by default javac has line numbers enabled, but variable names disabled. So you have to use -g to enable all debugging information. I have to document that.

**Comment by nikowitt** [comment]
Works like a charm, thank you!

**Comment by janschaefer** [comment]
Great :-)
