### ISSUE TITLE
HTML 5 report style feedback

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#129]
Hi Jan,

just my two cents about the HTML 5 report:
a) is it possible to customize the header "JGiven Report" in the HTML 5 report? I'd like to provide some additional build information.
b) when scenarios fail, is it possible to click the red spot on the status circle to directly see the failed scenarios?
c) is it possible to define some custom links in the the left menu? I'd like e.g. to provide a "Back to Jenkins" link

Best regards,
Niko

**Comment by janschaefer** [comment]
I assumed already that sooner or later the HTML report must become more customizable. The header will be easy. The links on the left a bit harder. Is there anything else you would like to have more customizable?

Regarding b) I created a new issue #130

**Comment by janschaefer** [comment]
Let's also hijack this ticket to make the report more customizable (I changed the title)

**Comment by nikowitt** [comment]
Probably I will find more spots where customizations when the reports are used by more people in our company. I'll of course let you know as soon as more feedback is available.

**Comment by nikowitt** [comment]
A quick solution for the links is to include some static link that refers to JS window.history.back().

**Comment by janschaefer** [comment]
I know ;-)

**Comment by nikowitt** [comment]
Debug info is given, the stacktraces of failing tests contain line numbers.

Am 28. September 2015 15:38:44 MESZ, schrieb Jan <notifications@github.com>:

**Comment by janschaefer** [comment]
Ok, maybe `-g:vars` is missing. I think by default `javac` has line numbers enabled, but variable names disabled. So you have to either use `-g` to enable all debugging information or `-g:lines,vars`. I need to document that.

**Comment by janschaefer** [comment]
Created #131 for the configurable title feature

**Comment by janschaefer** [comment]
Regarding the link thing. I am currently thinking about the best way such features could be implemented. One thing which come to my mind would be to allow the user to specify a custom Javascript file that is included in the report. Similar to the custom.css file. I would then provide a stable API that could be used by the Javascript file to customize the report. Something like:

```
jgivenReport.addLinkToNavigation("Some Link", "http://...");
```

It would enable a lot of possible options that would also be easy to be implemented. The only downside is that you have to write a bit of JavaScript. 

What do you think?

**Comment by nikowitt** [comment]
This is perfectly fine as this also makes the maintenance for multiple build easier. Additionally, it will give you a good handle to be able to deal with further customizations.

I then suggest to also make the title customizable via JS (as an alternative approach to set it via an --title as I saw in your recent commit).

Additionally, it is important is to be able to control the whole link properties via the JS, to be able to e.g. set target="_blank" - the URL alone might not be sufficient.

**Comment by janschaefer** [comment]
I have implemented this feature now. Please have a look at the scenario test which describes it quite well (you can also open the screenshot to see how it looks in the report):

http://jgiven.org/snapshot/jgiven-report/html5/#/scenario/com.tngtech.jgiven.report.html5.Html5AppTest/navigation_links_of_the_HTML_report_can_be_customized_using_a_custom_JS_file

**Comment by nikowitt** [comment]
It really looks great!

As already stated, the other common cases that already could be exposed via this API:
- title
- collapsed state of summary / tags / classes
- default sort by / group by/ status... of related views

**Comment by janschaefer** [comment]
I close this ticket now to get 0.9.0 released. I will provide additional configuration options with 0.9.1 (#135)
