### ISSUE TITLE
Ability to set global prefix per class to scenarios

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#133]
Hi Jan, some more feedback.

There are lots of security tests implemented that extend from a base class that also contains scenarios, e.g. "Validate create access" which is then called in a QuestionSecurityTestSuite and a ResponseSecurityTestSuite.

In the report, it is now difficult to see which scenario belongs to which test as there are just several "Validate create access" scenarios listed. A "group by class" (which is one additional click) solves this issue, but the class name might be too technical for non developers.

What would be great is to be able to define some global prefix by class that is prepended to the scenarios that are executed in the class. This way, the inherited generic "Validate create access" tests can have unique names (e.g. "Question - Validate create access" or "Response - Validate create access") and lots of wrapper methods that are only required to create unique names can be omitted.

Best regards,
Niko

**Comment by janschaefer** [comment]
That is an interesting suggestion. We also have a similar problem actually. The general problem is actually that one wants to group scenarios and give that group a name. The question is if the scenario should really be just prefixed or whether this should be a separate attribute of the scenario that could also be rendered differently in the report. It is somewhat similar to a tag with the exception that there can only be exactly one group name for a scenario.

**Comment by nikowitt** [comment]
Probably a separate attribute is indeed the better approach for this as it provides more possibilities to use this for other purposes. The scenario views should be then sorted by this attribute by default - when the attribute is not set, it will look like the "none" group by condition.

**Comment by janschaefer** [comment]
I implemented a first approach. Test classes can now have the `@As` annotation to give them a name. This name is then prefixed in the list of scenarios and can also be used to group them. I also changed the design of the group header. Let me know what you think:

http://jgiven.org/snapshot/jgiven-report/html5/#/all

**Comment by nikowitt** [comment]
Looks great, it is exactly what I've expected. What is also important IMHO is that the Class Title is the default group condition.

**Comment by janschaefer** [comment]
The more I use this new feature, the more I like it. I think this will be really useful. I like it so much that I now even generate a title for every class by using the class name and convert the camel case into readable text.

**Comment by nikowitt** [comment]
This is indeed a good default value :)

**Comment by nikowitt** [comment]
Is there a scheduled release date for 0.9? :)

**Comment by janschaefer** [comment]
If you want I can publish a SNAPSHOT version with what is currently there. You could use this then by including the sonatype snapshot repository (`https://oss.sonatype.org/content/repositories/snapshots`)

**Comment by nikowitt** [comment]
If it is not too much work for you, I'd be glad to be able to use that version in our environment.

**Comment by janschaefer** [comment]
Done. (It is about as much work as writing this comment ;-))

**Comment by janschaefer** [comment]
It is published under version 0.9.0-SNAPSHOT

**Comment by nikowitt** [comment]
Thanks, Jan! Have a nice weekend!

**Comment by janschaefer** [comment]
You are welcome!

**Comment by janschaefer** [comment]
I have configured travis now to publish a snapshot version of every successful build from master.

**Comment by nikowitt** [comment]
Even better :)
