### ISSUE TITLE
Ability to suppress parameters in case line when non-table report is rendered

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#134]
Hi, me again :)

Yesterday, I had a discussion with the test manager regarding the test cases, so I can share some more feedback.

The scenario contains a condition, so a non-table report is rendered, but each single case:
```
 Case 1: question1 = 4/null, question2 = null, holders = 4/5, 5/6, 6/7
   Given logged in system user
    When question "NEW 1" is created before question 4 with parent (not set)
     And numbering is refreshed
    Then numbering matches (old number/new number) 4/5, 5/6, 6/7
     And number field history is created

  Case 2: question1 = 2.1/2, question2 = null, holders = 2.1/2.2, 2.2/2.3
   Given logged in system user
    When question "NEW 1" is created before question 2.1 with parent 2
     And numbering is refreshed
    Then numbering matches (old number/new number) 2.1/2.2, 2.2/2.3
     And number field history is created
```

and so on. Something that caused confusion is that the params hat are included in the first line (e.g.   Case 2: question1 = 2.1/2, question2 = null, holders = 2.1/2.2, 2.2/2.3). Here, it is not easy to properly name them so a non developer can understand the meaning (OK, I can rename holders to something like oldPositionNewPosition here), but it is also not necessary, because in the report itself, the meaning of a parameter is pretty clear.

So what I think is useful to be able to suppress the printing of the variables in the first line when a non table report is printed. Maybe it makes sense to be able to provide an @Hidden annotation to the variables? I know that this might interfere with a table based report, but maybe this feedback is interesting for you.

Best regards,
Niko

**Comment by janschaefer** [comment]
Interesting. I think it really depends on the concrete scenario whether you want them to be shown or not, so some kind of mechanism to configure that would be needed. Using the `@Hidden` annotation would definitely be an option.

**Comment by janschaefer** [comment]
Btw. If you have other ideas to improve the way multiple cases are shown that are not using the data table, please let me know.

**Comment by janschaefer** [comment]
What do you think about #139?

**Comment by janschaefer** [comment]
I close this as #139 completely covers this case.
