### ISSUE TITLE
testng reports failing jgiven test cases as passing

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#138]
Given a TestNG-based test with a data provider
And the data provider provides at least two cases
And one case fails
When running the test
Then the TestNG report should contain one failed case

Instead all tests cases are reported as passing.
This behavior is since version 0.8.3.

**Comment by janschaefer** [comment]
So the TestNG report is wrong, but the JGiven report is correct?

**Comment by adrian-herscu** [comment]
Yes the JGiven report is correct but the TestNG report is wrong.
This has further implications. When running  under Maven the build status is always successful. When this happens under a CI server then not failure notifications are sent.

**Comment by janschaefer** [comment]
I actually introduced the bug when I fixed #123. Too bad that my test did not test the TestNg status, but only the JGiven status :-(
The bug is fixed now in the 0.9.1-SNAPSHOT version.

**Comment by janschaefer** [comment]
I back ported this fix to 0.8.x and will release a 0.8.4 version with that fix

**Comment by janschaefer** [comment]
0.8.4 is released with this fix

**Comment by janschaefer** [comment]
Due to the severity of the issue I also released v0.9.1 with this fix
