### ISSUE TITLE
Add possibility to define test-case name

### ISSUE THREAD

**Issue by Rubbiroid** [TNG/JGiven#139]
Hi,

if you use JGiven  use dataprovider to supply test cases, you may want to have a test-case description. Right now it can be done by calling an own method like given().the_test_case_is( description ), which is not a good solution IMHO.
Can you please provide a possibility to define a description of a test case? E.g. via special annotation of a test function argument.

Best regards,
Pavel

**Comment by janschaefer** [comment]
This goes into a similar direction as #134 and is actually a generalization of it.

**Comment by janschaefer** [comment]
@nikowitt this feature is now implemented. It would be cool if you could shortly test it on your side and tell me what you think. You use the feature by adding the ~@CaseDescription` annotation to the test method. With the value of the annotation you can specify the description. You can use the placeholders to insert parameter values. In the following example, I provide an additional value that is the description of the scenario and use the placeholder `$0` to refer to that description:

```
@Test
@DataProvider( {
      "This is the first case, true",
      "This is another case, false"
} )
@CaseDescription( "$0" )
public void custom_descriptions_of_cases_appear_as_a_separate_column_in_the_data_table(  
              String description, boolean value ) {
        given().the_power_light_$_on( value );
}
```

**Comment by nikowitt** [comment]
Sounds really cool - I will test this on Tuesday when I return to the office ☺

Am 9. Oktober 2015 17:09:48 MESZ, schrieb Jan <notifications@github.com>:

**Comment by janschaefer** [comment]
Sure :-)

**Comment by nikowitt** [comment]
OK, I've just tested it - is pretty fine for my cases. Something that is worth discussing is what happens if @CaseDescription is used and no @DataProvider is used. In this case, I expect the description to be displayed somewhere in my report even though it actually makes no sense to use the @CaseDescription here.

**Comment by nikowitt** [comment]
Some more feedback: In our history test, we want e.g. to include the return type of the field to be tested. The @DataProvider only contains the name of the field, but the actual type is determined at test runtime. Maybe it is also possible to be able to reference test scenario variables in @CaseDescription?

**Comment by janschaefer** [comment]
Mmh, I do not completely understand that. What do you mean by scenario variables? Could you make a short example?

**Comment by nikowitt** [comment]
Sure:

```
	@Test
	@DataProvider({
			"Supplier" + _ + Supplier.NOTES,
			"Supplier" + _ + Supplier.STATUS
	})
	@CaseDescription("updating field '$1'")
	public void test_log_history_entries(Class<? extends Base<?>> typeOfEntity, String fieldName) throws Exception {

		
		given().entity_of_$(typeOfEntity)
				.and().logged_in_system_user();

		// TODO: restore return type in description!
		String returnType = SumaHistoryTestSteps.getReturnType();
		when().user_updates_entity(fieldName);

		then().log_history_entry_is_created(fieldName)
				.and().log_history_displays_correct_values(fieldName, null);
	}
```

The issue why I cannot provide -SumaHistoryTestSteps.getReturnType();- in the DataProvider is that for this, the Spring context is not provided yet, so the value can only be calculated in the scenario itself.

**Comment by janschaefer** [comment]
I think in this case it should be possible to do the following:

```
 @CaseDescription( provider = CustomCaseDescriptionProvider.class )
...

static class CustomCaseDescriptionProvider implements CaseDescriptionProvider {

   public String description( String value, List<String> parameterNames, List<?> parameterValues ) {
       return "updating field "+parameterValues.get(1)+" type = " + SumaHistoryTestSteps.getReturnType();    
   }
}
```

does that work?

**Comment by nikowitt** [comment]
Yes, works perfectly :)
