### ISSUE TITLE
duplicated parameter column

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#140]
I have a test written as follows:

        when().creating_property_request(request)
                .and().getting_request_status();
        then().the_last_submitted_request_contained(request);

The method signatures are defined as follows:

    public SELF creating_property_request(final PropertyCreationRequest request)
    public SELF the_last_submitted_request_contained(final PropertyCreationRequest request)

If am not using a Formatter annotation, then one column is generated in the report, named request as expected.

However, if am adding a Formatter annotation to one or both signatures, then two columns are generated in the report, one named request and another named request2, both containing same information.

**Comment by janschaefer** [comment]
The expected behavior would be that if the String representation is identical then also only one column should be generated. It should not matter whether a formatter was used or not. Can you provide a small self-contained test that reproduces the problem?

**Comment by janschaefer** [comment]
@adrian-herscu do you have an update on this issue?

**Comment by adrian-herscu** [comment]
Sorry, couldn't find enough time to deal with it. Meanwhile, it is no issue for me.

**Comment by janschaefer** [comment]
Ok. Then I close the issue for now.
