### ISSUE TITLE
reports containing long values are unusable

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#141]
I need to test that some service accepts 4000 characters.

In such case, the resulting report becomes unusable because of the amount of horizontal scrolling needed to read the test case statuses (which appears as last column in the test cases table).

I solved this momentarily, by formatting the test parameters such as excessive text is truncated. However, this solution is not ideal, because one cannot reproduce the test simply by copying the text from the report.

A better solution would be to limit the text in each cell of the table to something reasonable (e.g. 100 chars), and if this limit is exceeded, then the text should be truncated and an ellipsis should appear to allow revealing the rest of it.

**Comment by janschaefer** [comment]
Sounds like a useful feature :-)
