### ISSUE TITLE
Create multiple tables instead of splitting into several scenarios

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#142]
Hi Jan,

a tricky one regarding several scenarios. The example is probably not the best one, but you definitely get the idea.

```
@Test
    @DataProvider({ XLSX_EXTENSION, PDF_EXTENSION, HTML_EXTENSION, "WORD" })
    public void create_sample_report(ReportFormat format) throws Exception {

        given().logged_in_system_user().and()
                .a_$_report("Sample Users Export", format, "FROM User Where id='<User>'", ReportEngine.getReportFromFileAsString(REPORT_USERS_EXAMPLE));
        when().report_is_rendered();
        then().no_errors_are_raised();
        if (format.equals(ReportFormat.XLSX)) {
            then().and().report_has_$_lines(10);
        }

    }
```

produces the output

```
Test Class: com.sobis.jaf.tests.services.output.report.ReportEngineTest

 Scenario: create sample report

  Case 1: format = xlsx
   Given logged in system user
     And a xlsx report
    When report is rendered
    Then no errors are raised
     And report has 10 lines

  Case 2: format = pdf
   Given logged in system user
     And a pdf report
    When report is rendered
    Then no errors are raised

  Case 3: format = html
   Given logged in system user
     And a html report
    When report is rendered
    Then no errors are raised

  Case 4: format = word
   Given logged in system user
     And a word report
    When report is rendered
    Then no errors are raised
```

In this case, it would be great if JGiven recognizes (or maybe provide a ability to control this) that it makes more sense to create two tables (or in this case, single case 1 and one table with cases 2-4). 

Maybe this is too tricky as this requires too deep code analysis, but maybe then it's a good idea to flag different cases that they are common and can therefore be aggregated in a table.

Best regards,
Niko

UPDATE maybe it helps if the provided params are analyzed, if they are null or not null (provided that the conditions in the test involve the provided params)...

**Comment by janschaefer** [comment]
Hi Niko,
that is indeed quite tricky and become arbitrary complex. I already have implemented a mechanism that tries to find the differences of different cases and highlight them in the HTML report. You may check if this is really the case for your example, but I know that it sometimes does not work correctly.
I could check whether it is easily possible to identify if multiple cases are really identical and put that into a different data table. But it will definitely require that I change a lot also in the underlying model and in the HTML report. So this will not be the highest priority task to work on ;-)

**Comment by nikowitt** [comment]
I'd expected that :)

My current workaround is to extract the scenario itself in a sub routine and then to provide multiple tests with different @DataProviders where I know that the cases are similar that run the subroutine.

So instead of doing an automatic parsing, some manual ability to group/flag cases is not the worst idea :)

**Comment by janschaefer** [comment]
Yes, this is also what we do in these cases :-). An advantage of this approach is also that you can give the groupings its own name.

**Comment by janschaefer** [comment]
I close this issue now as I think that manual grouping actually makes sense and an automatic approach is not worth the effort.
