### ISSUE TITLE
Jansi very old dependency

### ISSUE THREAD

**Issue by cmunger** [TNG/JGiven#1420]
jgiven core has a dependency on jansi 1.18 which is almost 5 years old, which is increasing the risk of dependencies problems with projects using the same library but with a more recent version like the 2.4.x version.

**Comment by l-1squared** [comment]
Thanks for bringing this to my attention.
I am a bit confused as to why renovte didn't fix that for me, but I will take a look tomorrow in the morning. (and release an update if applicable)

**Comment by cmunger** [comment]
thanks a lot, i started on working on it but saw someone fixed it last day, we had the same fix, thanks for the quick handling of this old dependency update

**Comment by l-1squared** [comment]
I'm glad to hear that you arrived at the same / a similar implementation for the issue :)

**Comment by l-1squared** [comment]
@cmunger  I have to humbly apologize that you have to wait for so long for such a simple fix. I attempted several releases over the last month, but unfortunately this PR https://github.com/TNG/JGiven/pull/1396 prevents this. It fails for releases only (some gradle dependency issue with the signing plugin) and my attempts to get this done quickly have now proven disastrous.  
Which unfortunately means that you have to wait a little while longer

**Comment by cmunger** [comment]
No problems, I was already amazed you did the fix so fast :)
