### ISSUE TITLE
ResolutionException

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#1427]
My program works fine from within Eclipse. Due to module dependencies on service provider starting the program from batch, it needs a module-path. This seems to be incompatible with exporting the program from Eclipse as a Runnable JAR FIle. Hence, I am trying to put all jars in one lib folder and start the main module. But I got an error:
```
java -p target/lib -m eu.ngong.ea2doors/eu.ngong.ea2doors.App RoS IFM_02
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules com.tngtech.junit.dataprovider.junit4 and com.tngtech.junit.dataprovider.core export package com.tngtech.junit.dataprovider.resolver to module commons.logging
```
In my Java-17 program ea2doors, I am refering to my utility module. That module is tested using JGiven and refers to a dataprovider:
```
		<dependency>
			<groupId>com.tngtech.jgiven</groupId>
			<artifactId>jgiven-junit</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.tngtech.junit.dataprovider</groupId>
			<artifactId>junit4-dataprovider</artifactId>
			<version>2.10</version>
		</dependency>
```
The only advice I found so far to resolve that error was to contact the module owners.

Is there any quick solution or do I have to stay away from JGiven to distribute my program?

**Comment by l-1squared** [comment]
Hi, 
I am a bit unsure as to what the issue here is. I'll try to take a closer look on monday

**Comment by l-1squared** [comment]
Hi @rolfschumacher,
first off all, I must regrettably inform you that I am actually not the owner of the JUnit Dataprovider. The relevant repo is here: https://github.com/TNG/junit-dataprovider.  Just to be safe though, I  checked both JGiven Junit and JGiven Core for the junit dataprovider dependency and concluded that we do neither bundle this dependency in the jar, nor do we mention it as a dependency in our pom.  So to me this looks as if JGiven would be entirely out of the game here.

The little help I can offer is as follows: Both JGiven and the JUnit4 Dataprovider should only be needed on the testClasspath. Maybe you can construct your export in such a way that it does not need them, assuming, of course the export is supposed to make its way to a production system. Alternativly, you could try to replace the dataprovider with JUnit5 and hope that that will resolve the resolution error.

**Comment by l-1squared** [comment]
I will close the ticket in 2 days if there is no further communication.
