### ISSUE TITLE
Support for JUnit5 Assumptions

### ISSUE THREAD

**Issue by j8zdev** [TNG/JGiven#1465]
JGiven currently supports assumptions from JUnit4 (`org.junit.AssumptionViolatedException`) and TestNG (`org.testng.SkipException`).

However, JUnit5's assumptions throw an `org.opentest4j.TestAbortedException`, which currently results in a failed test but should be handled in the same manner as the other supported exceptions.

**Comment by l-1squared** [comment]
You are probably right in that regard.
Could you help me out and provide an example test, or maybe even propose a fix?

**Comment by j8zdev** [comment]
@l-1squared: As far as I see, `org.opentest4j.TestAbortedException` needs to be added here: https://github.com/TNG/JGiven/blob/master/jgiven-core/src/main/java/com/tngtech/jgiven/impl/util/ThrowableUtil.java
