### ISSUE TITLE
Final step methods not working

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#148]
Hi Jan,

I've just discovered that it is also not possible to properly use final step methods - in my case, it looks like this:

```
public final T param_with_query_type_$_is_set(@QuotedReadableEnumWithExposedOrdinal Enum<?> queryType) throws Exception {
		int value = queryType instanceof JAFQueryType ? JAFQueryType.class.cast(queryType).getQueryType() : queryType.ordinal();
		return param_with_query_type_$_is_set(value);
	}

	/**
	 * Param_with_query_type_$_is_set.
	 *
	 * @param queryType
	 *            the query type
	 * @return the t
	 * @throws Exception
	 *             the exception
	 */
	public T param_with_query_type_$_is_set(@Quoted Integer queryType) throws Exception {
		getRequestParams().setQueryType(queryType);
		return self();
	}
```

When I supply an enum, the second method is used for formatting, the first (correct) method is not used. When I remove the "final" modifier, everything works as expected. Is this a bug or a CGLib limitation, so it should be documented?

Regards,
Niko

**Comment by janschaefer** [comment]
Yes that is completely right. This is a feature of Java ;-). But I will extend the documentation accordingly.

**Comment by nikowitt** [comment]
It's a pity since it makes sense to make some wrapper methods final, but very well :)

So this means CGLib cannot intercept final methods or is this a generic Java thing?

**Comment by janschaefer** [comment]
In order to intercept the method, cglib (and any other framework) has to override the method. This is forbidden by the definition of `final`, so it is not possible to intercept these methods (similar to `private` methods).
