### ISSUE TITLE
Suppress tests that don't have any stages?

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#151]
Hi Jan,

currently, we have got test classes that extend from a JGiven scenario and are therefore considered in the report (I assume that this is the condition) with both JGiven styled tests and lots of old styled tests with no given-when-then convention. In the report, the title of these old style tests is printed.

Shouldn't it be possible to exclude these tests automatically from the report as they are no real scenarios? I think there is already some annotation that allows the exclusion, but I don't want to annotate dozens of old tests...

Regards,
Niko

**Comment by janschaefer** [comment]
One could maybe add some flag to automatically exclude scenarios without any steps. I wouldn't like to do this by default, because it might be confusing. But in a mixed scenario like yours it would be useful. Maybe the best place for this would be the report generator.
