### ISSUE TITLE
Spring Boot with @WebIntegrationTest and Parameterized Tests

### ISSUE THREAD

**Issue by mind-blowing** [TNG/JGiven#169]
Hi,

I'm using JGiven for integration tests with Spring Boot ```@WebIntegrationTest```, it works fine when I'm using  annotation ```@RunWith(SpringJUnit4ClassRunner.class)```, but I also need to have possibility usage of Parameterized Tests and I can't use them because ```@RunWith``` already used with ```SpringJUnit4ClassRunner.class```.

I saw in spring framework reference documentation that it's possible to use ```@ClassRule``` with ```@Rule``` instead of ```@RunWith(SpringJUnit4ClassRunner.class)```

```
// Optionally specify a non-Spring Runner via @RunWith(...)
@ContextConfiguration
public class IntegrationTest {

   @ClassRule
   public static final SpringClassRule SPRING_CLASS_RULE = new SpringClassRule();

   @Rule
   public final SpringMethodRule springMethodRule = new SpringMethodRule();

   @Test
   public void testMethod() {
      // execute test logic...
   }
}
```

I tried to use approach with ```@ClassRule``` and ```@Rule```, but I got this error:
```
FAILED: Scenario is already initialized. This is most probably due to an internal defect in JGiven and was not your fault. Please consider writing a bug report at http://github.com/TNG/JGiven
```

Is it possible in JGiven v0.9.4 use Spring tests without ```@RunWith(SpringJUnit4ClassRunner.class)```?

**Comment by janschaefer** [comment]
You may have a look at https://github.com/TNG/junit-dataprovider/wiki/Tips-and-Tricks#dataprovider-for-spring-integration-testing

**Comment by mind-blowing** [comment]
Thanks a lot, I will try.

**Comment by mind-blowing** [comment]
It works, thanks again for help.
