### ISSUE TITLE
Figure out from which stage a method was called?

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#170]
Good morning,

is it possible to figure out from which stage a particular method was called? From the stacktrace itself, I cannot see if a method was invoked from given(), when() or then(). Since there are some method names (e.g. entity_is_deleted()) that basically need to invoke different logic depending on the stage they are called (in my case, given/when triggers an action whereas then is supposed to trigger a validation), my idea is to provide two cases in the implementation itself instead of implementing two separate methods to avoid confusion in simple scenarios.

Best regards,
Niko

**Comment by janschaefer** [comment]
No this is impossible, I think. Why don't you just use two different stage classes?

**Comment by nikowitt** [comment]
The problem is that these are methods that are included in a common stage collection that can be used in either scenarios or simple scenarios, so I cannot do this without adding configuration complexity (I wanted to avoid).

All right, I will then try to work on the names of the methods.

Thanks again!
