### ISSUE TITLE
jgiven-junit includes jgiven-html5-report, docs say differently?

### ISSUE THREAD

**Issue by tedyoung** [TNG/JGiven#180]
According to the install docs, using the HTML5 Reporter requires a separate dependency inclusion:

> ### HTML5 Report
> 
> JGiven provides a basic static HTML report. In order to get a model HTML5-based report you have to add the dependency in addition to the above dependency.

However, this line: https://github.com/TNG/JGiven/blob/master/jgiven-junit/build.gradle#L6 includes that dependency. Am I misunderstanding the docs here?

**Comment by janschaefer** [comment]
Yes. I am aware of that. The depencency was wrongly added as a compile dependency instead of a testCompile dependency. However, if I change it now, it might break clients that depend on that mistake. I might clean this up in the future with a corresponding changelog entry
