### ISSUE TITLE
Guide for migration from 1.x to 2.x

### ISSUE THREAD

**Issue by mmonetha** [TNG/JGiven#1803]
Hi there, 

I just saw that JGiven-2.0.0 has been released five days ago. Before I update the dependency, I wanted to check which changes lead to going from 1.x to 2.x. Unfortunately, I could neither find release notes nor a migration guide. Is there anything that has to especially be taking care of when updating JGiven to 2.x?

**Comment by m-2squared** [comment]
Well, the two main things that may produce issues are
* Java 17 now is the new minimum java version
* The gradle plugin now enforces excecution of test tasks it depends on.  So if you do not want that, you will now have to execute e.g. command line jgiven Reports  like `./gradlew jgivenReportTask -x test`. However, I'd wager that most implementations use `tests.finalizedBy(reportTask)`, as that is given in all the examples. For those, nothing changes.

Hope this helps

**Comment by l-1squared** [comment]
Well, the two main things that may produce issues are

Java 17 now is the new minimum java version
The gradle plugin now enforces excecution of test tasks it depends on. So if you do not want that, you will now have to execute e.g. command line jgiven Reports like ./gradlew jgivenReportTask -x test. However, I'd wager that most implementations use tests.finalizedBy(reportTask), as that is given in all the examples. For those, nothing changes.
Hope this helps

**Comment by mmonetha-sobis** [comment]
It does, thank you very much :smiley:
