### ISSUE TITLE
Typo in docs, section 'Getting started'

### ISSUE THREAD

**Issue by leoarnold** [TNG/JGiven#183]
The examples on the 'Getting started' page

http://jgiven.org/docs/gettingstarted/

use `GivenSomeState` (StaTe) in the first and `GivenSomeStage` (StaGe) in all others. Then again it's

    public GivenSomeStage some_state()

For consistency I suggest

    sed -i 's/GivenSomeStage/GivenSomeState/g'

**Comment by janschaefer** [comment]
thx
