### ISSUE TITLE
How to handle JUnit's assume() within JGiven

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#185]
In a BDD web testing setup I use a scenario "Given you use Firefox", that leads to an 

    assumeThat(c.getCapabilities().getBrowserName(), Matchers.equalToIgnoringCase("firefox"));

When running this on JUnit, it marks the test case as ignored due to an AssumptionViolatedException. 

Looking at the JGiven (HTML5) report it marks the scenario as failed. 

    Given 	you use firefox  !failed
    /* ...*/
    FAILED: org.junit.AssumptionViolatedException: got: "phantomjs", expected: equalToIgnoringCase("firefox")

There is currently no "Ignored" ExecutionStatus within JGiven, only Failed and Pending (including the filters in the HTML5 report). Should there be a new state Ignored?

Best regards,
Alexander

**Comment by janschaefer** [comment]
Ok, it should definitely be treated as pending and not as failed. Whether it is useful to introduce an Ignored state, I am not sure. In particular, tests that are Ignored by JUnit by the @Ignore annotation, might even not be trackable by JGiven.

**Comment by janschaefer** [comment]
The solution is as follows now: when throwing an AssumptionViolationException, the scenario will not appear in the report at all. This is identical to the case where a test is annotated with `@Skipped`

**Comment by phusilac** [comment]
@janschaefer I think that org.testng.SkipException should be treated the same way.
I would like to use [AssertJ assumptions](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.9.0-assumptions) to skip a TestNG test but when SkipException is thrown the test is marked as failed instead.

**Comment by janschaefer** [comment]
Totally agree. I opened a new issue for that #355
