### ISSUE TITLE
Global setup and cleanup 

### ISSUE THREAD

**Issue by ratulmukh** [TNG/JGiven#187]
Is there any way to do a global setup and cleanup before all scenarios are executed? I need to make long running database bootstrapping setup work before scenarios are executed. It is too time consuming to do it for every scenario in @BeforeScenario  methods.

**Comment by janschaefer** [comment]
JGiven currently provides no built-in mechanism for that. But you can use the mechanisms of JUnit/TestNG for that. For example, you could use a @BeforeClass-annotated method to do the setup for the whole test class.

**Comment by ratulmukh** [comment]
Ok, thank you.
