### ISSUE TITLE
ArgumentFormatter should allow HTML content formatting

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#188]
In simple cases we can use CR LF and spacing to format complex objects.
However, sometimes we have to format really complex objects, for example a DbUnit DataSet.
For a DataSet we may need to be able to generate an HTML table with column names and row values.
The current report simply renders the HTML tags, so something returned as "<b>hello world</b>" would be rendered the same in the report.

**Comment by janschaefer** [comment]
If you want to have a table you can use the `@Table` annotation that exactly does this

**Comment by adrian-herscu** [comment]
Appears that this is what I need. Tomorrow I will give it a try to see whether it suits my need.

**Comment by janschaefer** [comment]
Any updates on this?

**Comment by adrian-herscu** [comment]
Sorry, no time to deal with it.

**Comment by janschaefer** [comment]
I close this issue for now. Please reopen it if the `@Table` annotation did not work for you.
