### ISSUE TITLE
Format step method dynamically without parameters

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#189]
Hi Jan,

we've implemented some steps that are within some date ranges like this:

```
Given logged in user is system
     And  today is 2016-02-18
     And  response for rfqquestionnaire that is submittable by suma.contact@sobis.com
     And corresponding RfQ
    When start date is set to 2015-08-18 and due date is set to 2016-05-18
     And question changes
    Then no errors are raised
```

To be able to render the second (today) line, I need to supply the current date as a parameter, but I prefer to have a helper method like today() _without having to supply a parameter_. With @NestedSteps, this could be wrapped a little bit, but it is only a workaround. So basically I have to be able to have something similar to the CaseDescriptionProvider for step method that allows me to to some coding.

Is this already possible somehow?

Best regards,
Niko

**Comment by janschaefer** [comment]
Yes. This is actually something which I also wanted to have myself sometimes :-)

**Comment by Airblader** [comment]
So basically we need the provider mechanism in the `@As` annotation, right?

**Comment by Airblader** [comment]
I'm working on this. Just need to write tests, the rest is done.

@janschaefer Is there a specific reason why this pattern is called `*Generator` for some cases and `*Provider` for others?

**Comment by Airblader** [comment]
@nikowitt Would you mind taking a look at the PR to see whether the example I posted there covers what you originally asked for? Just want to make sure the implementation fits the request. Thanks!

**Comment by nikowitt** [comment]
Looks like a flexible solution hat fits the requirements.
