### ISSUE TITLE
Attachments with DataProvider in 0.11.1 as one file instead of several

### ISSUE THREAD

**Issue by mind-blowing** [TNG/JGiven#191]
We tried to update version of JGiven to 0.11.1, but found problem with attachments in tests when we are using DataProvider, instead of several attachment we have only one.

**Comment by janschaefer** [comment]
Corresponding scenario: http://jgiven.org/jgiven-report/html5/#/tag/Issue/%23191

**Comment by janschaefer** [comment]
Thanks for reporting!
