### ISSUE TITLE
Support more than one attachment per Step

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#194]
I've added an attachment to a step using CurrentStep#addAttachment to a step, then I tried a second attachment to the same step. 

I found that only the second attachment is presented in the report, as the model supports only one attachment at the moment.

As a user I would like to have multiple attachments on a single step to show for example request and reponse in the report. 

Thoughts?

**Comment by janschaefer** [comment]
Should basically be possible. The question is how to represent multiple attachments when there are mutliple cases with a data table. Currently the attachment symbols are numbered by case. If there are multiple attachments this will become confusing. Any ideas?

**Comment by ahus1** [comment]
In a scenario without a data table I would see two attachment symbols at the end of the line. When I hover over the attachment, the tooltip will give me a hint what I will find in the attachment.

In a data table I would expect the attachments belonging to the same row to have the same number. Like this: 

    This is a line [Att1]^1 [Att2]^1 [Att1]^2 [Att2]^2

**Comment by janschaefer** [comment]
I agree. That should be a good solution.
