### ISSUE TITLE
Html 5 report: Manage pending scenario with Dataprovider

### ISSUE THREAD

**Issue by fbouad** [TNG/JGiven#200]
When I use @Dataprovider and @Pending on my scenario, the report marks it as failed and not as pending.
It works fine when I only use @Pending on a scenario. Could you look at this please?

Thanks!

**Comment by janschaefer** [comment]
Interesting :-)

**Comment by janschaefer** [comment]
I could reproduce the problem. It is a design issue with JGiven that requires a backwards incompatible change of the JSON model. I will fix this with version v0.12

**Comment by fbouad** [comment]
Thanks!
