### ISSUE TITLE
Allow multiple formatters for one property

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#204]
Hi Jan,

```
public T superbox_query_type_$_with_query_$_is_prepared(@Hidden Class<? extends SuperBoxController> superboxClass,
			JAFQueryType queryType, @Quoted @NotSetIfNull String query) {
```
throws a

com.tngtech.jgiven.exception.AmbiguousFormattingException.

Is there any reason why multiple formatters can't be used in the order they are declared? To achieve that behaviour, I need to provide another formatter annotation that combines both formatters which results in increased code verbosity.

Best regards,
Niko

**Comment by janschaefer** [comment]
I think I originally couldn't think of a useful use case. But it seems to make sense to combine multiple formatters :-)

**Comment by Airblader** [comment]
The question coming to mind for me was "is the order of annotations returned when used reflection even guaranteed?". Luckily, [the answer is yes, albeit in a very hidden way](http://stackoverflow.com/questions/28067074/java-annotations-reflection-ordering).

**Comment by janschaefer** [comment]
Good to know :-)

**Comment by Airblader** [comment]
@janschaefer Do you have an easy way to implement this? I tried taking a go at it, but failed so far. My general idea was a "chained formatter" to collapse the list down, but the fact that `Formatter`, `ObjectFormatter` etc. have no common base is really getting in the way. Maybe I'm just misunderstanding the concepts here, though. Perhaps we can take a look at it in person sometime? :-)

**Comment by janschaefer** [comment]
I think that this has to be explicitly implemented in the core of JGiven. The main problem here is that the first formatter is different to the following formatter, because the first formatter takes the normal object as input, but the following formatter can only take Strings as input.

**Comment by Airblader** [comment]
@janschaefer Yeah. The following patch seems to work (not extensively tested, though) and shows the basic idea (it's not really cleaned up yet). I don't like all the casting that's going on, but the core, in that area, already heavily relies on casts and raw types and it doesn't seem trivial (or even possible?) to fix it. Maybe you can comment whether the basic idea of this patch is even the kind of thing you'd go for?

````
diff --git a/jgiven-core/src/main/java/com/tngtech/jgiven/impl/format/ParameterFormattingUtil.java b/jgiven-core/src/main/java/com/tngtech/jgiven/impl/format/ParameterFormattingUtil.java
index 946b882..f6350ba 100644
--- a/jgiven-core/src/main/java/com/tngtech/jgiven/impl/format/ParameterFormattingUtil.java
+++ b/jgiven-core/src/main/java/com/tngtech/jgiven/impl/format/ParameterFormattingUtil.java
@@ -5,13 +5,13 @@ import java.util.List;
 import java.util.Set;
 
 import com.google.common.base.Throwables;
+import com.google.common.collect.Iterables;
 import com.google.common.collect.Lists;
 import com.google.common.collect.Sets;
 import com.tngtech.jgiven.annotation.AnnotationFormat;
 import com.tngtech.jgiven.annotation.Format;
 import com.tngtech.jgiven.annotation.Table;
 import com.tngtech.jgiven.config.FormatterConfiguration;
-import com.tngtech.jgiven.exception.AmbiguousFormattingException;
 import com.tngtech.jgiven.exception.JGivenWrongUsageException;
 import com.tngtech.jgiven.format.ArgumentFormatter;
 import com.tngtech.jgiven.format.DefaultFormatter;
@@ -22,6 +22,8 @@ import com.tngtech.jgiven.format.table.TableFormatterFactory;
 import com.tngtech.jgiven.impl.util.AnnotationUtil;
 import com.tngtech.jgiven.impl.util.ReflectionUtil;
 import com.tngtech.jgiven.report.model.StepFormatter;
+import com.tngtech.jgiven.report.model.StepFormatter.ChainedFormatting;
+import com.tngtech.jgiven.report.model.StepFormatter.Formatting;
 
 public class ParameterFormattingUtil {
     private static final StepFormatter.Formatting<?, ?> DEFAULT_FORMATTING = new StepFormatter.ArgumentFormatting<ArgumentFormatter<Object>, Object>(
@@ -85,7 +87,15 @@ public class ParameterFormattingUtil {
         }
 
         if( foundFormatting.size() > 1 ) {
-            throw new AmbiguousFormattingException( "Found more than one formatting annotation at parameter " + parameterName );
+            Formatting<?, ?> innerFormatting = Iterables.getLast( foundFormatting );
+            foundFormatting.remove( innerFormatting );
+
+            ChainedFormatting<?> chainedFormatting = new StepFormatter.ChainedFormatting<Object>( (ObjectFormatter<Object>) innerFormatting );
+            for( StepFormatter.Formatting<?, ?> formatting: foundFormatting ) {
+                chainedFormatting.addFormatting( (StepFormatter.Formatting<?, String>) formatting );
+            }
+
+            foundFormatting = Lists.newArrayList( chainedFormatting );
         }
 
         if( tableAnnotation != null ) {
diff --git a/jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepFormatter.java b/jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepFormatter.java
index 1dd843e..b42e190 100644
--- a/jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepFormatter.java
+++ b/jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepFormatter.java
@@ -98,6 +98,33 @@ public class StepFormatter {
         }
     }
 
+    public static class ChainedFormatting<T> extends Formatting<ObjectFormatter<T>, T> {
+
+        private final ObjectFormatter<T> innerFormatting;
+        private final List<Formatting<?, String>> formattings = Lists.newArrayList();
+
+		public ChainedFormatting( ObjectFormatter<T> innerFormatting ) {
+			super( innerFormatting );
+			this.innerFormatting = innerFormatting;
+		}
+
+		@Override
+		public String format( T o ) {
+			String result = innerFormatting.format( o );
+			for( Formatting<?, String> formatting: formattings ) {
+				result = formatting.format( result );
+			}
+
+			return result;
+		}
+
+		public ChainedFormatting<T> addFormatting( Formatting<?, String> formatting ) {
+			formattings.add( formatting );
+			return this;
+		}
+
+    }
+
     public StepFormatter( String stepDescription, List<NamedArgument> arguments, List<ObjectFormatter<?>> formatters ) {
         this.stepDescription = stepDescription;
         this.arguments = arguments;

```

**Comment by Airblader** [comment]
Also, this currently throws a `ClassCastException` if non-string formatters are used in the wrong place. Should JGiven catch this and throw something else instead?

**Comment by janschaefer** [comment]
Cool. Thanks for having a look into this feature :-). Regarding the ClassCastException: yes this should be handled by JGiven, because it is actually a wrong usage of JGiven and not a fault in JGiven itself. In this case you should throw a JGivenWrongUsageException with a clear description of the problem.

**Comment by nikowitt** [comment]
I've just tested this feature in the new version (I've should have done this earlier :() and I don't think that in most cases, it is not a good idea to provide the JGivenWrongUsageException. There are many cases where I just want to quote the string representation of a particular field. Currently, I cannot e.g. use some @ReadableEnum @Quoted formatters, I still have to use a @QuotedReadableEnum and the original idea is to not be forced to define such additional classes.

What do you think?
Regards,
Niko

**Comment by Airblader** [comment]
I'm not sure I understand the problem. Don't you just have the two annotations switched? In other words you should use "@Quoted @ReadableEnum", assuming the latter turns an enum into a string.

**Comment by nikowitt** [comment]
My understand is that basically I want to apply the @ReadableEnum first and then to apply the @Quoted afterwards. But let's check :)

**Comment by Airblader** [comment]
Annotations aren't executed in order, but from "inner to outer" starting at the property. Admittedly in order is also a valid way, I think this comes down to preference.

**Comment by nikowitt** [comment]
Okay, this is fine to me now that I know :)

**Comment by Airblader** [comment]
Great. :-) Let us know if it worked!

**Comment by nikowitt** [comment]
Yes, it seems that it is working fine now. Thanks for the quick response!

**Comment by janschaefer** [comment]
thanks for testing! If you find anything else let us know :-)
