### ISSUE TITLE
Hide Tag from navigation on the left in HTML report

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#211]
I want to tag my test cases with IDs from the ticket system so I can use the IDs as a cross-reference and search for them. 

But the number of tickets would be too long on the navigation bar, therefore I would like to hide them from the navigation. 

Implementation idea: maybe add hideFromNavigation to IsTag annotation?

**Comment by janschaefer** [comment]
I would like to have a positive setting, something like `useForNavigation` and set it to `true` by default.

**Comment by Airblader** [comment]
I'd be happy to work on this after #172 (since this will affect the same area in the code).

**Comment by janschaefer** [comment]
I already started working on this :-)

**Comment by Airblader** [comment]
Then we'll have merge conflicts :-(

**Comment by janschaefer** [comment]
We will see, but I think we both have enough experience with merge conflicts ;-)

**Comment by Airblader** [comment]
Indeed, but I still prefer avoiding them. :-) We probably only have a conflict in `ScenarioModelBuilder` anyway. See #213.
