### ISSUE TITLE
Use consistent import settings throughout the codebase

### ISSUE THREAD

**Issue by Airblader** [TNG/JGiven#212]
It seems that the number of required imports before using `*` differs even within single classes which, with enabled import organization, causes a lot of unrelated noop changes. Since I don't want to commit those changes this requires me to manage change hunks which just needlessly wastes time. :-)

I think it'd be good if we could just agree on a sensible value for the number of required imports and then format all classes with that once.

**Comment by janschaefer** [comment]
Currently, I see that as a too minor issue to fix. It is not that important for me to have a completely consistent code base. I'll close it for now.
