### ISSUE TITLE
Add support for JUnit 5

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#220]
Create a new sub-project jgiven-junit5 to support JUnit 5

**Comment by janschaefer** [comment]
Fixed done #277

**Comment by Korop** [comment]
Do you plan to support release of JUnit 5? jgiven v0.15.1 looks like doen`t  compatible with

**Comment by janschaefer** [comment]
Yes, the API changed in the meantime. I created a new issue for that #326.
