### ISSUE TITLE
Just starting a project ...

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#222]
without BDD experience but like the idea to bind the test case coding to the test case documentation. I would like to see JGiven output prior to go for it but I cannot find any example html report to see how it will look like.
I did the _getting started_ including html reports and wonder not to see **Given some state. When some action then some outcome.** anywhere in the generated reports.
What did I miss?

**Comment by janschaefer** [comment]
On the start page of jgiven.org you can click on the screenshot and you will see the JGiven report of JGiven: 
* http://jgiven.org/jgiven-report/html5/
Another nice example is that of the xke project:
* http://janschaefer.github.io/xke-jgiven/
