### ISSUE TITLE
Custom ArgumentFormatter is not rendered the same in HTML report as in console

### ISSUE THREAD

**Issue by ctranxuan** [TNG/JGiven#226]
[jgiven-json-formatter.zip](https://github.com/TNG/JGiven/files/427378/jgiven-json-formatter.zip)

Hi,
I've tried to implement a json formatter (based on pretty print of the Jackson library).
When I apply my `@JsonPrettyFormat` annotation to a parameter, this one is well formatted in the console but not in the generated html report.

If I apply the formatting to a parameter without the annotation, the json is well formatted for both console and html report.

Please, find in attachment a sample to reproduce the issue.
I may have made a mistake in my `JsonPrettyFormatter` but I can't see which one.

Tested with:
- JGiven 0.11.4
- Java 8

Thanks in advance,
Cédric.

<details>
```java
public class JsonPrettyFormatterTest extends SimpleScenarioTest<JsonPrettyFormatterTest.JsonParserStep> {

    @Test
    public void return_a_json_object_with_properties_filtered() throws Exception {
        String json;
        json = "[{\"Outcome\":\"Success\",\"Delay\":0.0168215}," +
                "{\"Outcome\":\"Success\",\"Delay\":0.0}]";

        given().a_json(json); // <--- is not formatted as expected with the annotation
        then().the_json_is_well_formatted(JsonPrettyFormatter.prettyPrint(json)); // <--- is formatted as expected when formatting directly in the argument without the annotation
    }

    static class JsonParserStep extends Stage<JsonParserStep> {
        JsonParserStep a_json(@JsonPrettyFormat final String aJson) {
            return this;
        }

        void the_json_is_well_formatted(final String aExpectedJson) {
            Assert.assertTrue(true);
        }
    }
}```
</details>

**Comment by janschaefer** [comment]
Thanks for reporting and having provided a complete example!

**Comment by ctranxuan** [comment]
Thanks for JGiven and the fix!
