### ISSUE TITLE
Step methods with final modifier are not picked up in reports

### ISSUE THREAD

**Issue by patompa** [TNG/JGiven#227]
```java
 public final class DummyBDDTest extends SimpleScenarioTest<TestSteps>  {
    public static class TestSteps extends Stage<TestSteps> {
        public final TestSteps a_given() { return this; }
        public final TestSteps a_when() { return this; }
        public final void a_then() {}
    }
    @Test
    public void my_test() throws Exception {
        given().a_given().when().a_when().then().a_then();
    }
}
```

The a_given(), a_when(), and a_then() steps won't run or at least won't be reported unless I remove the final modifier from the methods. It would be great if the final modifiers would be allowed since not having them breaks the [checkstyle DesignForExtension rule](http://checkstyle.sourceforge.net/config_design.html).

**Comment by janschaefer** [comment]
Hi patompa,

due to the internal implementation of JGiven, step methods must be overridable. Otherwise JGiven cannot intercept the method calls. Thus, methods cannot be final, private or static.

Cheers,

   Jan
