### ISSUE TITLE
Attachment in JSON format in not written to a file

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#228]
If you define an attachment with MediaType JSON_UTF_8, no file is created by the HTML5 report. 

Html5AttachmentGenerator will create only files for "text/\*" and "image/\*" types.

I would expect to have a file regardless media type (maybe with a default extension of "bin" like binary). For "application/json" the extension should be ".json". 

Please comment if this is what other would expect as well. Thanks!

**Comment by janschaefer** [comment]
Yes, that should be fixed.

**Comment by ahus1** [comment]
Started working on this one.

**Comment by janschaefer** [comment]
Ok, great!
