### ISSUE TITLE
Reusing @Table

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#235]
Good morning,

I'm currently encountering the situation that I want to reuse a @Table
```
@Table(columnTitles = { ProjectPerformanceQuestionnaire.ON_TIME_DELIVERY,
				ProjectPerformanceQuestionnaire.PRODUCT_QUALITY,
				ProjectPerformanceQuestionnaire.SITE_CAPABILITY,
				ProjectPerformanceQuestionnaire.CLAIM_BEHAVIOUR }, includeNullColumns = true) 
```

I'd expected to be able to provide this as a meta annotation in my custom annotation as this is possible for other formatters, but this is not allowed. Is there an easy way of being able to do so?

Best regards,
Niko

**Comment by janschaefer** [comment]
The meta-annotation should definitely be implemented!

**Comment by janschaefer** [comment]
The fun fact is that it already worked, I only had to allow the `@Table` annotation to be applicable at annotations type.

**Comment by nikowitt** [comment]
Great. Too bad that the change was performed after the nightly build :)

**Comment by nikowitt** [comment]
FYI: Works fine with jgiven-core-0.12.2-20161101.222126-16.jar by using

```
	@Table(columnTitles = { ProjectPerformanceQuotationQuestionnaire.ON_TIME_DELIVERY,
				ProjectPerformanceQuotationQuestionnaire.PRODUCT_QUALITY,
				ProjectPerformanceQuotationQuestionnaire.SITE_CAPABILITY,
				ProjectPerformanceQuotationQuestionnaire.CLAIM_BEHAVIOUR }, includeNullColumns = true)
		@Retention(value = RetentionPolicy.RUNTIME)
		static @interface PPQTable {

		}
```
In this case, the annotation is a static inner class as it is only used in this test class.

**Comment by janschaefer** [comment]
Ok, cool. Thanks for testing!
