### ISSUE TITLE
[wish] call a method to generate @As message

### ISSUE THREAD

**Issue by sarahBuisson** [TNG/JGiven#237]
I wish I can have a way to process the message reporting by @As:

by Ex:

```

@As(method=buildMessage)
public void someMethode(String par1, String par2)

String buildMessage(String par1, String par2){
return par1.replaceAll(par2)
}
```

**Comment by Airblader** [comment]
The syntax you use for the example simply isn't possible in Java. The feature you want is already implemented as of 0.12.0 by using a provider. See 
 https://github.com/TNG/JGiven/blob/master/jgiven-core/src/main/java/com/tngtech/jgiven/annotation/As.java

**Comment by Airblader** [comment]
The one thing not possible is access to the arguments. @janschaefer

**Comment by janschaefer** [comment]
Maybe it still would be useful to support passing a method name as a string. This way you don't have to write a class.

**Comment by janschaefer** [comment]
That is in fact interesting. Currently the arguments are evaluated after the `AsProvider` has been called. In fact it would be better to let the `AsProvider` handle the arguments.

**Comment by janschaefer** [comment]
This is now implemented with a slightly different approach. See #386.
