### ISSUE TITLE
Introduce mandatory Scenario State

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#255]
It would be useful to have an attribute `mandatory = true` in the `@ScenarioState` annotation. If this is set, JGiven will fail if no such `@ScenarioState` would have been provided.

Example:
```
class MyStage {
    @ScenarioState(mandatory = true)
    String mandatoryState;
}
```

**Comment by Airblader** [comment]
There's also `@ExpectedScenarioState` and `@ProvidedScenarioState`, though I'd argue that this feature makes no sense in the latter of these two.

**Comment by janschaefer** [comment]
There is a problem with the new feature. When you have a scenario that is annotated with `@Pending` an exception is thrown when the field is not set. Expected behavior: the error should not be thrown.

**Comment by Airblader** [comment]
I think this would be rather dificult to fix in a clean way. Feel free to revert for now.

**Comment by janschaefer** [comment]
It was actually quite easy to fix :-)

**Comment by Airblader** [comment]
I wasn't aware that something like `suppressExceptions` already existed for pending tests. All the better. :-)
