### ISSUE TITLE
Access some global configuration

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#256]
Hi Jan,

I'd like to introduce some global flags (e.g. checking the last accessed stage or to determine whether exceptions are to be stored for further evaluation or if they are to be thrown directly) and to access these in my stages, but I don't want to use regular stage fields, but to e.g. access the scenario from my stage method and to then read global information. Is there a convenient way to do that? I can of course access the stages from a scenario, but not vice versa (without supplying them as an additional property on my own)? Or maybe this stuff could be put inside the JGiven configuration which then also needs to be referred to from my stages?

Regards,
Niko

**Comment by janschaefer** [comment]
Why not just using a @ScenarioState for that? :-D

**Comment by janschaefer** [comment]
Ok, I just saw that you don't want to use Stage fields, but actually I see no reason why not to use them. You could introduce a new class `MyPersonalGlobalScenarioState`. You could have a common super class for all of your stage that has that field, so you can use it in all of your stages.

**Comment by nikowitt** [comment]
You're right, just providing this shared config works fine. Thanks for the hint!
