### ISSUE TITLE
Nested steps are not reported with jgiven-spring

### ISSUE THREAD

**Issue by s-bortolussi** [TNG/JGiven#259]
Hi

When running a [spring scenario test](https://github.com/TNG/JGiven/tree/master/examples/spring-boot/src/test/java/com/tngtech/jgiven/example/springboot) with  ```@NestedSteps``` , it seems that nested steps are not reported. 

Did I miss something in my config ?

Thanks for your help

**Comment by janschaefer** [comment]
You don't have to configure anything for that to work. Might be a bug. I will try to reproduce that.

**Comment by janschaefer** [comment]
I could reproduce the issue and it is harder to fix then expected.

**Comment by s-bortolussi** [comment]
@janschaefer thanks for the update
