### ISSUE TITLE
Meta Tags

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#27]
As a developer,
I want to be able to organize my tags hierarchically,
so that I get a better overview over my tags.

Idea:
Allow tags to be tagged by meta-tags. These meta-tags should also appear in the report and should allow for a hierarchical structuring of the tags in the report.

Example:
In order to hierarchically structure features under the meta-tag `@Feature`. We define an annotation `@Feature`:

```
@IsTag
@Retention( RetentionPolicy.RUNTIME )
public @interface Feature { }
```

Then we annotated feature tags with that tag:

```
@Feature 
@IsTag( type = "Feature", value = "Data Tables",
    description = "In order to get a better overview over the different cases of a scenario<br>"
            + "As a human,</br>"
            + "I want to have different cases represented as a data table" )
@Retention( RetentionPolicy.RUNTIME )
public @interface FeatureDataTables { }
```

The resulting report should then show something like this:

```
Feature
 - Data Tables
 - ...
```
It should also be collapsible

**Comment by nobeh** [comment]
While working on this enhancement, can the meta data be extended to also support customized CSS/HTML elements for the tags?

For example, we have added two tag definitions `@Story` and `@Bug` to annotated test scenarios. The tags are properly generated and we can navigate through them. However, it would be very nice to have a another annotation attribute to accept a custom CSS class for the tag that comes from `custom.css`. For example:

```java
public @interface IsTag {
    String cssClassName() default ""; // Or the default can come from Foundation
}

```

**Comment by janschaefer** [comment]
Great idea! I created a pull request to track that feature: #69

**Comment by janschaefer** [comment]
I close this issue as a duplicate of #90
