### ISSUE TITLE
Would it be useful to have @BeforeStep and @AfterStep hooks?

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#273]
Currently it is not easily possible to do an action before every step or after every step. Would you think that it make sense to introduce such life-cycle hooks? One example use case would be to take a screenshot after every step, for example.
As an alternative we could also introduce a listener interface that is attached to the stage. Something like:

    @StepListener( MyStepListener.class )
    public class MyStage {
    } 

    public class MyStepListener implements StepListener {
         public void before(CurrentStep currentStep) { 
             ....
         }
         public void after(CurrentStep currentStep) {
             ....
         }
    }

**Comment by janschaefer** [comment]
Duplicate of #328

**Comment by ahus1** [comment]
As a workaround for the missing `@AfterStep` I started to override the self() method assuming that I call it at the end of each step.
