### ISSUE TITLE
HTML Report: Show small preview images instead of an Attachment Icon for Image Attachments

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#274]
In case of images as attachments it would be nice to have an option of showing small preview images instead of showing the attachment icon. This should be configurable when generating the HTML report.

**Comment by cirquit** [comment]
What would be the better solution - to store the name of the thumbnail in the AttachmentModel class, or to just save it as "title-thumb"?

**Comment by janschaefer** [comment]
just save it as 'title-thumb' for now.
