### ISSUE TITLE
HTML Report: Have the option to show an image attachment as a popup

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#275]
Currently when clicking to an attachment icon a new browser page is opened. It would be more convenient, in particular for images, if a popup would be shown that shows the image. It might be useful to have this configurable.

**Comment by cirquit** [comment]
Should this be a popup that is embedded in the html and is activated via a click? The other option would be an image that pops up if you hover over the thumbnail, and is gone after you move the mouse away

**Comment by janschaefer** [comment]
It should not open when hovering, but when clicking on the thumbnail. Then an overlay should be shown with the image, so that the attachment is not opened in another tab, for example.

**Comment by janschaefer** [comment]
See: http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html

**Comment by cirquit** [comment]
It seems like none of these snippets want to work in the report. The buttons exist and are clickable, but no modal is shown. The modal doesn't change the value `visibility: hidden` and `display:none` after a click.

If these are changed manually the dialog is visible but not closable.

**Comment by janschaefer** [comment]
Mmmh, maybe the Foundation Javascript is not included.

**Comment by cirquit** [comment]
I included the foundation javascript and implemented the popup. There are still some minor errors:

- How can I include the foundation.min.js to every build? (I've done it manually until now)
- After a reload the `$(document).foundation()` at the end of the `index.html` does not seem to work. I have to run it in the console to take action
- The group-by bar suddenly disappears if I click on any image

Here is a [webm](https://webmshare.com/KE1YM) of the last problem.
My fork of the current version: https://github.com/cirquit/JGiven/tree/issue275-image-preview-on-click

**Comment by janschaefer** [comment]
The point should be easily handled by just adding an import statement to the 'entry.js' file. The 2nd and 3rd point, I don't know.

**Comment by janschaefer** [comment]
Closing the issue here as it will be handled in https://github.com/jgiven/jgiven-html-app/issues/4
