### ISSUE TITLE
Automatically update Jenkins plugin after every release

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#290]
Hi Jan,
the latest Jenkins JGiven plugin uses JGiven 0.10. Is it possible to also automatically provide an updated Jenkins plugin (I know that you are not the plugin responsible, but probably its best when you coordinate that :)) )

Thanks!
Regards,
Niko

**Comment by janschaefer** [comment]
yes, I am aware of that problem. I recently have applied for the rights to publish the Jenkins plugin myself and I have the rights now, but I am still struggling with the upload of the plugin. I always got a timeout error, so far. I will try it again today.

**Comment by janschaefer** [comment]
Ok, I managed to upload the plugin now :-). It can take some time (about 8 hours) until it shows up in the update center.

**Comment by nikowitt** [comment]
Very nice, thank you!

**Comment by janschaefer** [comment]
It is in the update center now :-)

**Comment by ahus1** [comment]
I previously used the Jenkins plugin, but actually discontinued its use, as the JGiven version creating the JSON output needs match the version of the Jenkins plugin. 

I switched to adding a post-build action to create the report and to publish the HTML report using Post Build Action.

**Comment by nikowitt** [comment]
Hi there, 0.15.0 does not yet seem to be available in the update center?
Regards, Niko

**Comment by janschaefer** [comment]
True. I will try to publish it today.

**Comment by janschaefer** [comment]
Ok, I have to change some code in the Jenkins plugin to get it working again. I will do this today. So expect the plugin to be ready tomorrow.
