### ISSUE TITLE
Memory consumption in JGiven 0.14.0

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#294]
Hi there,

currently, we're not able to run our builds successfully after updating to JGiven 0.14.0 as they simply stuck (so it's a memory issue). Rolling back to 0.13.0 solves the issue. As I currently cannot provide any specific information, can any experience be shared regarding memory consumption (due to ByteBuddy?)?

Regards, 
Niko

**Comment by janschaefer** [comment]
You are the first one that reports this issue. I will investigate that.

**Comment by janschaefer** [comment]
Could you tell me which Java version you are using? Have you tried, as a workaround, to inrease the memory?

**Comment by nikowitt** [comment]
Java/JVM detail version: 1.8.0_72-internal

Regarding memory increase, I'll let you know after I've talked to the admin.

**Comment by nikowitt** [comment]
Builds are not completed yet, but it seems that increasing the memory helps here.

**Comment by janschaefer** [comment]
Ok. Thank you very much for the investigation! Just to narrow down the issue further: are you using Spring?

**Comment by nikowitt** [comment]
Yes, Spring 4.2/Hibernate 4.3 (I know, we need to update :) ) - but we are using the DataProviderRunner approach using SimpleScenarios and Scenarios.

**Comment by janschaefer** [comment]
Ok. Then it may also be related to the new Spring implementation.

**Comment by janschaefer** [comment]
It turns out that ByteBuddy, in contrast to cglib, does not cache generated classes. That most likely causes this issue.
