### ISSUE TITLE
Support for spring boot test

### ISSUE THREAD

**Issue by machielg** [TNG/JGiven#295]
I'm writing integration tests using the following annotations:
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)

It would be great if JGiven could be used to power the integration tests.

**Comment by janschaefer** [comment]
Spring is fully supported by JGiven. 
You can find a Spring Boot example here: https://github.com/TNG/JGiven/blob/master/example-projects/spring-boot/src/test/java/com/tngtech/jgiven/example/springboot/HelloControllerTest.java. 
Documentation: http://jgiven.org/userguide/#_spring

**Comment by janschaefer** [comment]
I close this issue now. Feel free to reopen it again if you think I missed something.
