### ISSUE TITLE
reporting in a constrained Jenkins environment

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#296]
Our Jenkins environment does not allow having report pages with JavaScript inside, and perhaps without various other advanced CSS and fonts features.

Is there a static report?
If needed, what would be the best way to write a custom report generator?
Meanwhile, is it possible to have the plain text report emitted into some file?

**Comment by janschaefer** [comment]
* The Jenkins problem is already known. Maybe you can configure the Jenkins to allow Javascript? See #176 for a discussion
* Currently, there is no static HTML report. Writing a report generator is also no trivial task. However, you could have a look at the PlainTextReporter as a starting point if you would like to contribute one (you are very welcome!). Note, though, that the PlainTextReporter is not fully featured. E.g. Attachments and Tags are not reported.
* You can generate text reports by setting the format option of the report generator to 'text'. This will generate `.feature` files, containing the scenarios.

**Comment by janschaefer** [comment]
I will close the issue for now as 'wontfix', because a static HTML report is currently not on the list of planned features. *However*, as I said above, you are very welcome to implement one if you want to!

**Comment by adrian-herscu** [comment]
Is there a way to have an index.html file generated to link all the generated scenarios?
Perhaps, a Jenkins way to do this?

**Comment by adrian-herscu** [comment]
Yet another question... What would be the best place to install my reporting hook?

**Comment by janschaefer** [comment]
Have you tried the JGiven Jenkins plugin? It can also generate text files. https://wiki.jenkins-ci.org/display/JENKINS/JGiven+Plugin

**Comment by adrian-herscu** [comment]
We are bound to use a draconian managed Jenkins instance. Currently, it makes JGiven totally unusable. Must find a solution quickly. Thinking about converting the JSON files to XML, then writing some XSLT to generate one big HTML file.

**Comment by janschaefer** [comment]
Ok, I see. Using XSLT would definitely be possible. As an alternative you can inherit from `AbstractReportGenerator` and write the generator in Java

**Comment by adrian-herscu** [comment]
Hmmm... Inheriting from `AbstractReportGenerator ` means forking JGiven itself (?) Or, is there a way to supply my "generator" from the outside?

**Comment by janschaefer** [comment]
It is currently not possible to supply a custom generator to the JGiven report generator, however, the JGiven report generator is more or less only a very small wrapper around calling instances of `AbstractReportGenerator`. So for now you could write a simple class with a main method that does what the current `ReportGenerator` class does. Essentially the following:

      CompleteReportModel model = new ReportModelReader( config ).readDirectory( jsonDir );
      StaticHtmlReportGenerator reportGenerator = new StaticHtmlReportGenerator();
      reportGenerator.generate( model, targetDir, config );

where `StaticHtmlReportGenerator` inherits from `AbstractReportGenerator` and `config` is an instance of `ReportGenerator.Config`.
