### ISSUE TITLE
Make HTML5 report tables filterable or exportable

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#305]
Hi Jan,

> I'd like to share some internal feedback about the JGiven reports, maybe you can also comment this.
> 
> I really like the JGiven reports that we are using now. Though with the huge number of tests that we are facing, it is sometimes very hard to validate test results.
> As you can see in my attached screenshot we have sometimes more than 2000 cases...
> 
>![image](https://cloud.githubusercontent.com/assets/1472328/23071043/64ac148e-f52d-11e6-968b-53fe8221a322.png)
> The only practicable way for me the check these cases is to select the cases table in the browser window and copy and paste it to MS Excel.  Here I can set filters in the columns and search for the relevant cases.
> 
> Although this solution works it is very annoying and time consuming because
> - the selection within the browser window is difficult because I have to ensure that I only select the table and therefore I have to scroll down (very slowly)
> - I have to format the copied values in MS Excel.
> 
> So I wonder if the JGiven Report can be improved in some way?
> 
> Here some ideas that would help me:
> - enable to set of multiple filters in the HTML table
> - a download link that provides automatically the report as XLS, CSV or XML file
> - a "select table" link on top of the HTML table 

Having such a big table in the report indeed takes 30-40 seconds to expand on my machine, so probably leaving the browser and to be able to use Excel might be very helpful here.

Best regards,
Niko

**Comment by janschaefer** [comment]
I agree. The tables are not designed to scale to so many cases. 
- Download as CVS should be easy to implement
- Adding paging would make sense to improve performance
- Filters should also not  be too hard.
- It might be useful to evaluate some JS libraries that support all that out of the box.

**Comment by janschaefer** [comment]
I think http://ng-table.com/ would be a good match for the requirements. @nikowitt what do you think?

**Comment by nikowitt** [comment]
That indeed looks very nice :) The only remaining question is how to control the initial page size.

**Comment by janschaefer** [comment]
wirh a sensible default? We could also make it configurable.

**Comment by janschaefer** [comment]
Closing this issue here as it will be handled in https://github.com/jgiven/jgiven-html-app/issues/2
