### ISSUE TITLE
Use ByteBuddys own cache implementation

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#310]
Since v1.6.0, ByteBuddy provides its own cache implementation. This should be used instead of JGiven's own implementation.

**Comment by janschaefer** [comment]
@mustaine sure, there are two classes that implements caching. I think I meant the second one with this ticket, but I cannot 100% remember anymore :-) 

- jgiven-core/src/main/java/com/tngtech/jgiven/impl/util/FieldCache.java
- jgiven-core/src/main/java/com/tngtech/jgiven/impl/CachingStageClassCreator.java

**Comment by l-1squared** [comment]
Apparently this is already resolved
