### ISSUE TITLE
Help : how to include one's own resource (css, img, ...) in jgiven report target site

### ISSUE THREAD

**Issue by dgrandemange** [TNG/JGiven#316]
Hi,

My use case : in several scenario, i need to join dynamically generated html attachments to my steps.

These dynamic html are generated using some kind of handmade template mechanism (don't need a velocity for this). Original html template relies on a external constant resource file (a json file in my case that holds some business specifications, but it could have been an external stylesheet or images, whatever).

My question : is there a way to add constant resources files somewhere in my test project, so that theses resources are directly included in the produced jgiven report site, so that it can be further be loaded by my html attachments ?
If not, can the step attachement mechanism help me in any way ? For instance, i can think of getting my resources attached through a dedicated step in a dedicated scenario. But that would be quite tedious. Besides, this is not the purpose of a scenario.

Well, any help would be great.

Damien

**Comment by ahus1** [comment]
The HTML reports allows for a custom JavaScript and CSS resource (one per report). This is not stated in the documentation, but in you'll find it in the source code. See here [for the Maven plugin](https://github.com/TNG/JGiven/blob/master/jgiven-maven-plugin/src/main/java/com/tngtech/jgiven/maven/JGivenReportMojo.java) and [for the Gradle plugin](https://github.com/TNG/JGiven/blob/1f8fc7f31dabe719cff63125ba8afbc9bea6cc5c/jgiven-gradle-plugin/src/main/java/com/tngtech/jgiven/gradle/JGivenReport.java).

**Comment by janschaefer** [comment]
As ahus1 said, you can specify a JS file and a CSS file to copy to the target report. There is no general mechanism though. The attachment feature might not really help here, because the path of the attachment is not really static as it depends on the class name and scenario name. What you could do, however, is to just copy the files yourself into the generated report folder. 
If, however, you want to dynamically load JSON files, the browser will not alliw that when using the file protocol.

**Comment by dgrandemange** [comment]
Hi,

And thank you both for you help.
About custom JS and CSS, i indeed knew about this, as i checked the maven plugin source for any tips in the first place, but didn't consider it a solution at a first glance.

I actually chose another way with Maven Resources Plugin : 
by attaching it to the _verify_ phase, and placing it below jgiven-maven-plugin declaration in the pom.xml, i've been able to copy extra resources (goal `copy-resources`) under the jgiven-report target folder after jgiven execution.
But that was only the first part of the challenge...

Second part was to load these resources from theJGiven attachments. 
First, as Jan mentionned it, an attachment is generated under a specific folder hierachy based on scenario class package. So, from the attachement current location, i had to dynamically retrieve the relative path to traverse URL path back to the resource folder. Besides, having this relative path built, i realized (after some consequent time and struggle) that loading a resource in parent folder was not allowed (at least locally). So, Jan, you are absolutely right about that.

So the only workaround i found this far :
instead of making my HTML attachment load my JSON resource to do its job, this job is delegated to a mutualized HTML resource (not an attachment) placed under jgiven-reports/html folder (aside/above all other extra resources it may require to do its job). On the other side, the HTML attachement becomes a redirection page toward this mutualized HTML resource. (Indeed, unlike jquery/ajax load, there is nothing preventing a page to relocate itself to a page higher in the path.)
Works fine.

**Comment by janschaefer** [comment]
Ok, interesting approach, thanks for sharing! What you can also do is to load JSONP resources with the <script> tag. That is how the JGiven report itself is loading the report data.
