### ISSUE TITLE
NullPointerException raised by POJOAnnotationFormatter.format(...)

### ISSUE THREAD

**Issue by dgrandemange** [TNG/JGiven#318]
Hi again, 

Lately, i face a situation where
`POJOAnnotationFormatter.format(java.lang.Object argumentToFormat, Formatf annotation)`
raise a `NullPointerException`.

This occurs when received parameter `argumentToFormat ` is null.
My `POJOAnnotationFormatter` implementation clearly misses something here.
This could be fixed by early inserting a check to test if `argumentToFormat` is null, and if that is the case, immediatly return null which, IMHO, is better than returning an empty string (can't see any indication about this in interface `AnnotationArgumentFormatter.format(java.lang.Object argumentToFormat, Formatf annotation)` contract though.)
By returning null (rather than an empty string), this make this null POJO object further evictable when part of a `@Table` formatting where attribute `includeNullColumns` is set to `false`.

**Comment by janschaefer** [comment]
Hi,
this is somehow related to #315. I am not sure about your suggested solution. The format method should return a String and it should never be null actually (documentation is not precise here), because other JGiven code depends on this (see discussion in #315).

**Comment by dgrandemange** [comment]
Ok, thank you for the clarification.

Datatable examples have been completed to reproduce the issue.
The fix simply consists in returning a "null" string in case given object is null, and is available in PR #319.

**Comment by janschaefer** [comment]
Fixed by #319
