### ISSUE TITLE
JUnit Parameterized Test HTML report 

### ISSUE THREAD

**Issue by SaleemKhair** [TNG/JGiven#322]
Is it possible to have the scenario repeated instead of having place-holders followed by a data table?

**Comment by janschaefer** [comment]
No that is currently not possible. JGiven always tries to create a data table if that is possible. The best solution would be to implement a feature in the HTML report to switch between both views. I consider this a feature request :-)

**Comment by janschaefer** [comment]
Closing this issue here, because it will be handled in https://github.com/jgiven/jgiven-html-app/issues/1
