### ISSUE TITLE
NPE in jgiven-html5-report: Unzipping /com/tngtech/jgiven/report/html5/app.zip

### ISSUE THREAD

**Issue by sradi** [TNG/JGiven#323]
Hi,

in version 0.14.1 of jgiven-html5-report, there was an app.zip contained in the library. In 0.15.*, this is missing.
I am seeing this output, when I run com.tngtech.jgiven.report.ReportGenerator --format=html...

```
11:16:30.180 [main] DEBUG c.t.j.r.config.ConfigOptionParser - setting the argument value: format to HTML
11:16:30.225 [main] DEBUG c.t.j.r.config.ConfigOptionParser - setting the argument value: format to HTML
11:16:30.225 [main] DEBUG c.t.j.r.config.ConfigOptionParser - setting the argument value: sourceDir to jgiven-reports
11:16:30.225 [main] DEBUG c.t.j.r.config.ConfigOptionParser - setting the argument value: targetDir to jgiven-reports\html
11:16:30.570 [main] INFO  c.t.jgiven.report.ReportGenerator - Generating HTML5 report to C:\...\jgiven-reports\html\index.html
11:16:30.575 [main] DEBUG c.t.jgiven.report.ReportGenerator - Unzipping /com/tngtech/jgiven/report/html5/app.zip...
Error: JGivenReport has encountered the following exception: java.lang.NullPointerException: in is null
```

Is my assumption correct, that this is a bug?

best regards
Stefan

**Comment by janschaefer** [comment]
Hi,

sorry for the late answer. How exactly are you running the ReportGenerator? I think this is a classpath issue. Since 0.15.0 the app.zip is in a different jar file (jgiven-html-app-0.15.0.jar). The report generator has a dependency on that jar. I am closing this issue now. If this issue is still valid, please reopen it.

Best regards,

   Jan

**Comment by sradi** [comment]
Hi,

I manually added the JGiven libraries to our OSGi target platform. But obviously I missed the new jar "jgiven-html-app". Thanks for the hint!

Best regards
Stefan
