### ISSUE TITLE
Screenshots don't work if an alert is present

### ISSUE THREAD

**Issue by IroshR** [TNG/JGiven#333]
html screenshots failed on alert popup

jgiven.version - 0.15.3

String base64 = ((TakesScreenshot) webDriver).getScreenshotAs(OutputType.BASE64);
currentStep.addAttachment(Attachment.fromBase64(base64, MediaType.PNG).withTitle("screenshot"));

throw an UnhandledAlertException exception:
threw 'org.openqa.selenium.UnhandledAlertException' exception.

**Comment by janschaefer** [comment]
I don't think this is a JGiven issue. It more looks like Selenium has an issue in taking the screenshot. JGiven only takes the result from Selenium and stores it as an image. JGiven is not really involved in creating the screenshot.
