### ISSUE TITLE
Does JGiven support bean definition by groovy bean configuration?

### ISSUE THREAD

**Issue by hyd198471** [TNG/JGiven#336]
At the moment I try to integrate our spring boot application with jgiven. I saw the example. Jgiven use component scan to look up the beans when it annotated as JGivenStage. In our project I don't want to use component scan because we use groovy bean configuration files. For example i create a beans-jgiven.groovy file and use beans{ myBean MyBean} to define my beans. However it doesn't support by jgiven. It will throw `java.lang.ClassCastException: com.wewash.service.appliance.jgiven.GivenACurrencyDomain$$EnhancerBySpringCGLIB$$792e025e cannot be cast to com.tngtech.jgiven.impl.intercept.StageInterceptorInternal`. 
Any idea How can i solve this problem?

**Comment by janschaefer** [comment]
Could you provide a minimal example project, so that I can easily reproduce the problem?

**Comment by chrisime** [comment]
Hello @janschaefer 
we will come up with a minimalistic example.

thanks,
Christian

P.S. Grettings from Jan Allenberg ;-)

**Comment by janschaefer** [comment]
Ok, great. Perfect would be if you could create a fork of JGiven and create a failing test case. 

P.S: Greetings back :-)

**Comment by janschaefer** [comment]
Btw, if you already have an idea how that could be fixed in JGiven, let me know.

**Comment by mustaine** [comment]
should we close this issue ? Have been more than a year

**Comment by janschaefer** [comment]
Yes, let's close it.

**Comment by chrisime** [comment]
@janschaefer that's fine, AFAIK WeWash switched to annotation based configuration.
