### ISSUE TITLE
Using stages written in Kotlin

### ISSUE THREAD

**Issue by zambrovski** [TNG/JGiven#350]
I'm trying to use JGiven with Kotlin. In doing so, I'm interested in writing stages and tests in Kotlin.

For tests it seems to work without any problems, but for stages the `@BeforeStage` annotated function seems not to be called. Copying it back to Java solves the problem.

I'm using the "inherited" approach:

```
open class MyGivenStage : Stage<MyGivenStage>() {
  
  @BeforeStage
  open fun init() {
    // this code is never called
  }
  
  open fun `something happens`() : MyGivenStage {
    
    return self()
  }
}
```

Any ideas?

**Comment by zambrovski** [comment]
Ok I managed to get it running. Stages must be `open`, the initialization method too, the properties marked with `@ScenarioState` should be `lateinit var` (non-private).

In order to get `@ScenarioState` values injected, ALL methods of the stages must be marked as `open`

So everything works fine, sorry for wrong issue.

**Comment by janschaefer** [comment]
Cool! Do you have by chance a minimal example project which we could put into the example-projects folder?

**Comment by zambrovski** [comment]
I'll contribute it as a pull request...

**Comment by keesvandieren** [comment]
@zambrovski have you made the PR? I searched for it, but could not find it :-)
