### ISSUE TITLE
documentation: accessDenied on class references

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#357]
I click on the  "SimpleScenarioTest"  link in the current userguide (http://jgiven.org/userguide/#_use_jgiven_with_junit_5).

The URL is:  http://static.javadoc.io/com.tngtech.jgiven/jgiven-junit5/0.15.3/com/tngtech/jgiven/junit5/SimpleScenarioTest.html

But instead of the code, I see:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

**Comment by janschaefer** [comment]
Thanks for the report. It works now. The problem was that on javadoc.io had not downloaded the files. I triggered it by visiting the main page of the documentation `http://javadoc.io/doc/com.tngtech.jgiven/jgiven-junit5/0.15.3`. Not sure what the best long-term solution is though.
