### ISSUE TITLE
Like to see a maven example with Java-9 or -10

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#360]
It would be great to have an JGiven/maven example based on J-9. As module-info.java is a new subject it is not as easy to do set it up correctly. Also what is a working project layout that works with maven and preferably with m2e. I am used to separate the application and the tests and would like to have no test information in a release built.

Do you know of an maven archetype including JGiven and a module-info.java?

**Comment by janschaefer** [comment]
No there is no maven archetype yet. We have an open issue for that https://github.com/TNG/JGiven/issues/97.

**Comment by rolfschumacher** [comment]
did a first attempt: https://gitlab.com/ngong1/mvnArchtype4JGiven
