### ISSUE TITLE
Prototype scope with @JGivenStage should be documented or enforced

### ISSUE THREAD

**Issue by arnor2000** [TNG/JGiven#362]
Hi,

The fact a stage in Spring context (annotated with `@JGivenStage` or other) must have a prototype scope should be documented at least in `JGivenStage` javadoc and JGiven user guide as a reminder.

I don't see any case where a `JGivenStage` shouldn't have prototype scope because `@ProvidedScenarioState` fields are not reinitialized between tests execution and thus given context is messed up by previous test cases.

If there is no reason to have singleton stage, maybe the prototype scope should be enforce when stages are used with Spring.
I don't know if adding annotation `@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)` on `JGivenStage` is enough to activate this behavior or if it must be done in `JGivenBeanFactoryPostProcessor`.

**Comment by janschaefer** [comment]
Yes. The `JGivenStage` must have prototype scope. Best solution would be to enforce it, I agree.

**Comment by ahus1** [comment]
I've added a PR #371 that picked up @arnor2000's idea. Comments welcome.

**Comment by arnor2000** [comment]
Thank you both!
