### ISSUE TITLE
ExpectedScenarioState Rule not available in BeforeStage

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#364]
I have an externalResourceRule in my Test that I provide via `@Rule @ProvidedScenarioState`.

I have access to the rule in my Steps#methods. But during the `@BeforeStage` execution, it is still null.

That's not nice, because now I have to workaround with `@Hidden` given steps.

**Comment by janschaefer** [comment]
which JUnit version do you use?

**Comment by jangalinski** [comment]
4.12 and jgiven 0.16

**Comment by janschaefer** [comment]
I cannot reproduce this. My test is green :-). See linked test case.

**Comment by janschaefer** [comment]
Closing for now. Feel free to reopen.
