### ISSUE TITLE
Powermock

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#365]
When I try to create test using powermock (class annotated with `@RunWith(PowerMockRunner.class)`)
Jgiven logging does not work and json report is not generated

**Comment by ahus1** [comment]
Could you please publish a minimal example that shows the problem? This would help to investigate what's going wrong.

**Comment by nnar1o** [comment]
sample project: https://github.com/nnar1o/powermock-jgiven-test

**Comment by janschaefer** [comment]
Thanks for the example. I can confirm that it is not working.

**Comment by janschaefer** [comment]
I reopen the issue, because the mentioned workaround of adding `@PowerMockRunnerDelegate( BlockJUnit4ClassRunner.class )` is also not working. The workaround enables Class Rules again, but due to some other PowerMock behavior it is not working either.

**Comment by janschaefer** [comment]
Issue will be fixed with v0.16.1 and the mentioned workaround.

**Comment by f3mshep** [comment]
I was able to resolve this issue by annotating the test class with the following:
`@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(BlockJUnit4ClassRunner.class)`
