### ISSUE TITLE
JUnit 5: support for tags

### ISSUE THREAD

**Issue by olmorigolo** [TNG/JGiven#367]
Hello, I updated all of my jgiven tests to use junit5 as I want to take advantage of its features in the future.

Well, I hoped that Junit 5 Tag and Tags are automatically transformed into jgiven tags, but they are not shwon on the report. Do I need to implement a AbstractJGivenConfiguration on my own?

Will this be integrated in the future?

Thanks

**Comment by janschaefer** [comment]
As you already suspected, this is already possible by implementing a subclass of `AbstractJGivenConfiguration`. I have extended the JUnit5 example to show how to this. Please see the commit above. However, as this is a feature that I assume everybody wants to have out of the box, I will leave this ticket open as a feature request.

**Comment by l-1squared** [comment]
already implemented
