### ISSUE TITLE
Java 11 does not support sun.misc.Unsafe any longer

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#370]
tried to use JGiven with Java 11 results in
`Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe`

I suppose this is because of using Java 11 due to **[JDK 11 and proxies in a world past sun.misc.Unsafe](http://mydailyjava.blogspot.com/2018/04/jdk-11-and-proxies-in-world-past.html?m=1)**

Is there a way to use JGiven with Java 11 in the near future (or did I interpret the failure message wrongly)?

**Comment by janschaefer** [comment]
Yes. I already start working on Java 11 support. It is a bit more effort than expected, because of other JGiven dependencies.

**Comment by janschaefer** [comment]
Fixed it by upgrading to the newest ByteBuddy version and fixed some other small issues.

**Comment by pzygielo** [comment]
The newest BB has this: https://github.com/raphw/byte-buddy/commit/f3148185ceedb74a3b7383b6f706fa99fca4c438 and JGiven broke for me on Java 25 now, once I bumped BB.

Per the [BB comment](https://github.com/raphw/byte-buddy/commit/f3148185ceedb74a3b7383b6f706fa99fca4c438#r187449549):
>  You would need to avoid this strategy and use `UsingLookup` instead which is the only approach that the JVM supports in the near future.
