### ISSUE TITLE
Disabled test causes NullPointerException when using subclassable stage

### ISSUE THREAD

**Issue by wulfsberg** [TNG/JGiven#376]
JUnit 5.3.2, JGiven 0.17.0

Using the generics notation for a subclassable test Stage:
````
import com.tngtech.jgiven.Stage;

public class ExtensibleReproStage<SELF extends ExtensibleReproStage<SELF>> extends Stage<SELF> {
  public SELF something() {
    return self();
  }
}
````

When a test scenario uses this class and has a @Disabled test, the following test will crash as `given()` returns null:

````
import com.tngtech.jgiven.junit5.SimpleScenarioTest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class ReproTest extends SimpleScenarioTest<ExtensibleReproStage> {
  @Test
  @Disabled
  void test1() {
    given().something();
  }
  
  @Test
  void test2() {
    // given() returns null when following test1
    given().something();
  }
}
````
This does not happen with a "normal", non-subclassable Stage

This is likely somewhat related to #338

**Comment by wulfsberg** [comment]
In fact, I get a similar NullPointerException in a more complex test suite without using subclassable  generics, but I cannot find a clear repro case for that situation.

**Comment by janschaefer** [comment]
Thanks for the report. I could reproduce the issue and found the problem.
