### ISSUE TITLE
Report skipped scenarios

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#384]
When I use org.junit.Assume and mark scenario as skipped there is no information in the report about skipped scenarios. It would be nice to have them displayed the same way as Pending scenarios.

**Comment by janschaefer** [comment]
Mmh. This is currently the intended behavior, but I tend to agree that skipped would make more sense. This would be a breaking change though.

**Comment by janschaefer** [comment]
In fact, I tend to say that this is not the same as a pending scenario. The pending annotation actually marks a scenario as not implemented yet. Skipped because of a failed assumption has a different meaning.

**Comment by m-2squared** [comment]
To me it appears as if this is equivalent to #1625

**Comment by l-1squared** [comment]
Appears to be equivalent to #1625
