### ISSUE TITLE
flexible step names - @As annotation access to class fields

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#386]
I have a scenario:
```
@Test
void test(){
  given().member_first_name();
  when().member_is_enrolled();
  then().first_name_is_valid();
}

class GivenMember {
  @ProvidedScenarioState
  String firstName;

  GivenMember member_first_name(){
    firstName = random();
  }
}

class ThenMember {
  @ExpectedScenarioState
  String firstName;

  @ExpectedScenarioState
  Member enrolledMember;

  GivenMember first_name_is_valid(){
    assertThat(enrolledMember.getFirstName()).isEqualTo(firstName);
  }
}
```

Is it possible to have in the report a dynamic step name that will include values from the stage (and not only method arguments)?
I.e.: something like this:
```
@ExpectedScenarioState
String firstName;

@As("first name of enrolled member is $firstName")
GivenMember first_name_is_valid()
```
Or somehow extend the AsProvider class to have access to ExpectedScenarioState fields? Maybe Other option can be adding a new method setStepName(String name) and call from method to adjust it's name in the report.

Now the workaround that I use in my code is like this ( this is ugly but works):

```
then().first_name_is_(given().getFirstName());
```

Best regards and thanks for help

**Comment by janschaefer** [comment]
Interesting suggestion and also quite useful I think. There is already a possibility to inject the current step by using the `@ScenarioState` annotation together with the `CurrentStep` interface. See http://static.javadoc.io/com.tngtech.jgiven/jgiven-core/0.17.1/com/tngtech/jgiven/CurrentStep.html for details. I think this could be easily extended to be able to set the step name.

**Comment by janschaefer** [comment]
Done. You can now do the following:

````
@ScenarioState
CurrentStep currentStep;

@ExpectedScenarioState
String firstName;

GivenMember first_name_is_valid() {
     currentStep.setName("first name of enrolled member is " + this.firstName);
}

**Comment by nnar1o** [comment]
When do you plan to release a new version?

**Comment by janschaefer** [comment]
Is released no in version 0.18.0

**Comment by gandadil** [comment]
I can't see the Name property anywhere in HTML report, just on JSON report. Maybe HTML report is not reflecting the change?

**Comment by janschaefer** [comment]
Yes, indeed, you are right.

**Comment by janschaefer** [comment]
I think I have not really thought this feature to the end. While updating the words array would be possible, the argument information would get lost. In parametrized scenarios this would mean that when the step name changes, JGiven will not be able to create data tables.

**Comment by janschaefer** [comment]
I fixed this and updated the documentation to make clear that data tables cannot be created. Otherwise this should work now with the next 0.18.2 release.
