### ISSUE TITLE
Provide scenarioTests with 2 stages (instead of 3 or 1)

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#388]
We have been using jgiven for quite a while now and found that we tend to always use an in-between base class which is not <GIVEN, WHEN,THEN> nor <ALL> but <GIVENWHEN, THEN>.

Motivation: when working with tests on multiple state changes, the when-part of the first test becomes part of the given-part of the next ... while the "assertion" (then) stage remains the same. (we use this in process tests and cqrs aggregate tests, where the state of the system-under-test ist dtermined by a sequence of actions).

So we came up with something like

     ActionAssertScenarioTest<ACTION_STAGE, ASSERTION_STAGE> extends ScenarioTest<ACTION_STAGE, ACTION_STAGE, ASSERTION_STAGE>

and use it as base class of our tests.

I would love to have that in jgiven directly as an alternative to the SimpleScenarioTest<ALL>, or working with class hierarchies for GIVEN and WHEN stages.
I think the change is a small one, just provide the mentioned abstract base class.  
What do you think? would you be open for a PR?

**Comment by janschaefer** [comment]
Sure, should be no problem. Do you have a good name for such a class?
