### ISSUE TITLE
Add `example-projects` to the build

### ISSUE THREAD

**Issue by jsalinaspolo** [TNG/JGiven#392]
Would be interesting to add the `examples-projects` to the build? So they do not get out-of-date?

**Comment by janschaefer** [comment]
I explicitly did not want to add them to the build as the examples should be completely self-contained. Maybe they can be added to the Travis build though.

**Comment by mustaine** [comment]
I think would be interesting that the examples are built somehow. What do you think if we add those examples as part of the JavaDoc and it is compiled to ensure they work?

**Comment by janschaefer** [comment]
Could you provide a PR that shows how this could be done?
