### ISSUE TITLE
Question: Build failing 

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#399]
I have two issues I'd like to contribute to, but when I do `git clone` and `gradle clean build`, the current master fails with:

```
com.tngtech.jgiven.gradle.JGivenPluginTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/xxx/.gradle/caches/5.1/generated-gradle-jars/gradle-api-5.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/xxx/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.25/8dacf9514f0c707cbbcdd6fd699e8940d42fb54e/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext]

com.tngtech.jgiven.gradle.JGivenPluginTest > configure_reports FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JGivenPluginTest.java:115

com.tngtech.jgiven.gradle.JGivenPluginTest > jgiven_test_results_are_written_to_the_buildDir FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JGivenPluginTest.java:58

com.tngtech.jgiven.gradle.JGivenPluginTest > jgiven_html_report_is_generated FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JGivenPluginTest.java:90

com.tngtech.jgiven.gradle.JGivenPluginTest > configure_html_report FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JGivenPluginTest.java:139

com.tngtech.jgiven.gradle.JGivenPluginTest > jgiven_test_results_can_be_written_to_custom_directory FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at JGivenPluginTest.java:74

8 tests completed, 5 failed

```

Is this a known issue? I experienced it on two different machines ...

**Comment by janschaefer** [comment]
I think it is a version issue of your local Gradle installation. Did you try ./gradlew clean build?

**Comment by jangalinski** [comment]
I meant `./gradlew` 

tried again, still failing. This error from the HtmlApp5Test looks suspicious:

     java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html

does the build require some external manual setup?

**Comment by janschaefer** [comment]
Should not be the case. It builds on Travis without any manual setup.

**Comment by mustaine** [comment]
@jangalinski did you install phantomjs as is mentioned in [contributing](https://github.com/TNG/JGiven/blob/master/CONTRIBUTING.md#system-requirements)?

`npm install -g phantomjs-prebuilt`

**Comment by janschaefer** [comment]
Ah right, completely forgot about that :-). Would be good to get rid of that dependency...

**Comment by janschaefer** [comment]
I replaced PhantomJS with Headless Chrome with PR #401. I will merge to master as soon as Travis is successful.

**Comment by janschaefer** [comment]
Is merged now to master. PhantomJS is not needed anymore.

**Comment by mustaine** [comment]
nice @janschaefer
