### ISSUE TITLE
part of json reports not created when running in testng parallel mode

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#409]
Not having enough time to prove this, but it seems that `ScenarioTestListener` class incorrectly manages its `reportModels`. This field is defined as a non-final instance and is overridden during `onStart`. The observed effect is that when running with `suite parallel="tests"`, all defined test classes are executed but not all `json` files are generated.

https://github.com/TNG/JGiven/blob/master/jgiven-testng/src/main/java/com/tngtech/jgiven/testng/ScenarioTestListener.java#L111

**Comment by janschaefer** [comment]
Fixed by not using any field anymore.
