### ISSUE TITLE
Ability to display large list of scenarios

### ISSUE THREAD

**Issue by rprabhu2503** [TNG/JGiven#412]
Hi
Currently JGiven displays data directly from json file generated by the test execution. It loads everything in memory and manages the display using Pagination. In case where one has huge list of test execution results it would crash JGiven ui as it would overflow the memory. To support large set of data can we support storing test execution output in oracle database and use the same to display in the UI. Please correct me if I have misundertood things as I have limited usage exp with JGiven. Would appreciate a quick response. 
Thanks
Rajesh

**Comment by janschaefer** [comment]
Yes. Everything is loaded into memory, except for attachments which are only loaded on demand. Theoretically it would be possible to store the data in some database instead. In addition, a web server would be needed that provides a suitable REST interface.

**Comment by janschaefer** [comment]
Could you tell how many Scenarios you have?

**Comment by rprabhu2503** [comment]
Thanks for asking the question. We are building a product which contains 10 features and each may have say 200 tests per MVP including integration and E2E. This makes it 2000 per scenarios per MVP overall on upside. Please can you let me know if its handled in the current state and if not what we can do.

**Comment by janschaefer** [comment]
2000 Scenarios should be no problem.

**Comment by rprabhu2503** [comment]
Thanks a lot for the feedback. Have you experienced any limit beyond which it gives memory issue. I know it will depend on the memory available but are you aware of a memory config which is recommended and the max scenario count it would support. Thanks

**Comment by janschaefer** [comment]
Roughly calculated I would say that a single Scenario takes up about 1 kB (without attachments, but they are loaded independently). Even if you would have 100.000 Scenarios, this makes about 100 MB. So the probability of reaching any memory limit is very low.

**Comment by rprabhu2503** [comment]
Ok and thanks for the prompt clarification.
