### ISSUE TITLE
TestEntityManager initialize to null

### ISSUE THREAD

**Issue by ksundaysky** [TNG/JGiven#415]
Hi,

I'm trying to inject TestEntityManager to Stage.

I use @DataJpaTest. My test class look like this:

```java
@RunWith(SpringRunner.class)
@DataJpaTest
@EnableJGiven
public class BookedRentalJGivenJpaTest extends SpringScenarioTest<BookedRentalGiven, BookedRentalWhen, BookedRentalThen>
```

And if I want to inject TestEntityManager to Given stage:
``` java
@JGivenStage
public class BookedRentalGiven extends Stage<BookedRentalGiven> {

@Autowired
private TestEntityManager testEntityManager;
```
it is initialized to null and NPE is thrown.

Am I doing something wrong?

**Comment by jackblack81** [comment]
Same for me

**Comment by janschaefer** [comment]
Could you check the Spring logs for errors? Because I was able to inject the TestEntityManager. See https://github.com/TNG/JGiven/blob/master/example-projects/spring-boot/src/test/java/com/tngtech/jgiven/example/springboot/JpaTest.java

**Comment by Hatzen** [comment]
I m facing the same issue. I guess the difference in your samples is that you are using a SimpleSpringRuleScenarioTest<Stage> instead of SpringScenarioTest<GivenStage, WhenStage, ThenStage> then annotation is only applied to the givenstage in my case

**Comment by leimer** [comment]
You can use SpringRuleScenarioTest<GivenStage, WhenStage, ThenStage> as a workaround.
It appears, that Rules make the difference. I don't know if this is on purpose. But for now you can at least have three different stages. I am going to look into that.

**Comment by leimer** [comment]
Okay, I found the reason. Lets look at the documentation of `@DataJpaTest`

> Annotation that can be used in combination with `@RunWith(SpringRunner.class)` for a typical JPA test. Can be used when a test focuses only on JPA components.
**Using this annotation will disable full auto-configuration** and instead apply only configuration relevant to JPA tests.
By default, tests annotated with `@DataJpaTest` are transactional and roll back at the end of each test. They also use an embedded in-memory database (replacing any explicit or usually auto-configured `DataSource`). The `@AutoConfigureTestDatabase` annotation can be used to override these settings.

As you can see, `@DataJpaTest` disables the auto-configuration. This also includes the default Spring-Boot `@ComponentScan` which would pick up the Stage classes (`@JGivenStage` is meta-annotated with `@Component`).

As a workaround you can just define this on your test class: 
`@ComponentScan(includeFilters = @ComponentScan.Filter(JGivenStage.class))`
But be aware this will activate every JGivenStage in your project. Which also means you need to provide every dependency the stages need. Those are normally not active in a DataJpaTest. To fine-tune that you can adapt the `@ComponentScan` to your needs.

I am also thinking about adding this to the `@EnableJGiven` annotation and make it overwriteable by the meta-annotation mechanism of Spring. I will discuss that with @janschaefer.
