### ISSUE TITLE
allow custom scaling of attachment thumbnail

### ISSUE THREAD

**Issue by adrian-herscu** [TNG/JGiven#417]
For performance reasons, I am transforming my screenshots to use less colors and also scale them down to 1/4 so their sizes are now approx. 300x550 and weight less than 14KB.

Now I am discovering that the attachment thumbnails are no longer visible :(
This is due to [hardcoded scaling value](https://github.com/TNG/JGiven/blob/master/jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java#L158), currently set at 0.02.

**Comment by janschaefer** [comment]
What would be a good solution? I think a fix thumbnail size would make more sense, right?

**Comment by adrian-herscu** [comment]
> What would be a good solution? I think a fix thumbnail size would make more sense, right?

I would say that this would be the cheapest solution :)

**Comment by janschaefer** [comment]
What would be a good solution? I think a fix thumbnail size would make more sense, right?

**Comment by adrian-herscu** [comment]
> What would be a good solution? I think a fix thumbnail size would make more sense, right?

Sounds reasonable as long as it will display proportionally on different screen resolutions.

**Comment by janschaefer** [comment]
I just looked into the code and it is already implemented that the thumbnail should have a minimal width and height of 20px. Maybe this is just too small?

**Comment by janschaefer** [comment]
Ok, after understanding the code, I think the minimal size is not applied correctly...

**Comment by janschaefer** [comment]
Fix is released with v0.18.0. Can you verify that it works for you?
