### ISSUE TITLE
JGiven Localization

### ISSUE THREAD

**Issue by gandadil** [TNG/JGiven#423]
I need to localize html report to portuguese. Is there any way to do that or can this be implemented as a new feature? I am using SimpleScenarioTest extends

**Comment by gandadil** [comment]
Just to complement, I am using SimpleScenarioTest

**Comment by janschaefer** [comment]
Depending on what you want to localize. Do you want to localize your scenarios? This is already possible. See for example `EscenarioTest` for a Spanish version of the standard `ScenarioTest`. What this does, however, is mainly replacing the standard `given`, `when`, `then` methods with translated ones. The HTML report itself currently has no localization support, this would have to be implemented.

**Comment by gandadil** [comment]
I need exactly this, the Given, When, Then tags translated to Dado, Quando, Então (portuguese). Can this done and in SimpleScenarioTest class too?

**Comment by janschaefer** [comment]
This is not a problem. If you could provide a translation file like this one for portuguese: https://github.com/TNG/JGiven/blob/master/jgiven-core/src/main/translations/es.properties
I can include that in the next release.

**Comment by gandadil** [comment]
Well, I don't have permission to create a branch and commit, so here is the translation:

scenario_test_class=CenarioTeste
scenario_test_javadoc=
scenario_test_base_class=CenarioTesteBase
scenario_test_base_javadoc=
stage_class=Etapa
stage_javadoc=Uma versão em português da classe {@link com.tngtech.jgiven.Stage}.
given_type=DADO
when_type=QUANDO
then_type=ENTAO
given_words=dado,dada
when_words=quando
then_words=entao
intro_words=e,mas,com
comment=comentario

**Comment by janschaefer** [comment]
Alright, thanks. I will add the file.
