### ISSUE TITLE
JGiven + testng running three times with dataprovider

### ISSUE THREAD

**Issue by gandadil** [TNG/JGiven#427]
I have a test with JGiven + testng + selenide to run my e2e tests. Every time I set a dataprovider the 
I don't know why but my tests are running three times. I am not asking for that. When I run the group e2e on test bellow, this problem is not occuring.

```java
public class LoginTest 
    extends SimpleScenarioTest<LoginStage>
{
	
	@Test(groups="e2e")
	public void testeDeLoginComUsuarioPaulo() {
		given().estou_na_tela_de_login();
		when().preenchi_usuario_$_e_senha_$("paulo", "12345678")
		.and().cliquei_no_botao_logar()
		.and().selecionei_empresa_Contente();
		then().abrira_a_tela_home();
	}
	
	@Test(groups="e2eRecursivo", dataProvider="DadosLogin", dataProviderClass = DataProviderClass.class)
	public void testeDeLoginRecursivo(String usuario, String senha) {
		given().estou_na_tela_de_login();
		when().preenchi_usuario_$_e_senha_$(usuario, senha)
		.and().cliquei_no_botao_logar()
		.and().selecionei_empresa_Contente();
		then().abrira_a_tela_home()
		.and().saira_do_sistema();
	}
}
```
and my DataProviderClass

```java
public class DataProviderClass {


	
	//Exemplo de carga de dados estáticos
	@DataProvider(name="DadosLogin")
	public static Object[][] retorarDadosParaTesteDeLogin(){
		return new Object[][] {
			{"paulo", "12345678"},
			{"paulo", "12345678"},
			{"paulo","12345678"}
		};
	}
```
my testng.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="testes_e2e" verbose="1">
	<test name="e2eRecursivo" parallel="false" preserve-order="true">
		<groups>
			<run>
				<include name="e2eRecursivo"/>
			</run>
		</groups>
		<classes>
			<class name="com.ui.web.e2eTest.LoginTest" />
		</classes>
	</test>
	
	<test name="e2e" parallel="false" preserve-order="true">
		<classes>
			<class name="com.ui.web.e2eTest.LoginTest"/>
			<class name="com.ui.web.e2eTest.GerenciarNFeTest" />
			<class name="com.ui.web.e2eTest.HomeTest" />
			<class name="com.ui.web.e2eTest.BaseTestClass" />  
		</classes>
	</test>
</suite>
```
my maven install command line is:
install -Dmaven.test.failure.ignore=true -Dselenide.browser=chrome -Dgroups=e2eRecursivo

RESULTS:

Test Class: com.ui.web.e2eTest.LoginTest

 Teste de login recursivo

   Given estou na tela de login
    When preenchi usuario paulo e senha 12345678
     And cliquei no botao logar
     And selecionei empresa Contente
    Then abrira a tela home
     And saira do sistema

  Cases:

   | # | Status  |
   +---+---------+
   | 1 | Success |
   | 2 | Success |
   | 3 | Success |

Test Class: com.ui.web.e2eTest.LoginTest

 Teste de login recursivo

   Given estou na tela de login
    When preenchi usuario paulo e senha 12345678
     And cliquei no botao logar
     And selecionei empresa Contente
    Then abrira a tela home
     And saira do sistema

  Cases:

   | # | Status  |
   +---+---------+
   | 1 | Success |
   | 2 | Success |
   | 3 | Success |

Test Class: com.ui.web.e2eTest.LoginTest

 Teste de login recursivo

   Given estou na tela de login
    When preenchi usuario paulo e senha 12345678
     And cliquei no botao logar
     And selecionei empresa Contente
    Then abrira a tela home
     And saira do sistema

  Cases:

   | # | Status  |
   +---+---------+
   | 1 | Success |
   | 2 | Success |
   | 3 | Success |

[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.749 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

**Comment by janschaefer** [comment]
But has it anything to do with JGiven? Is this also happening if you are not using JGiven?

**Comment by gandadil** [comment]
Well, I did some tests without JGiven and the same is occurring. My problem is something related with testng because if I remove the tag <classes> from my testng.xml the problem gone.
Sorry for the false report.

**Comment by janschaefer** [comment]
Thanks for verifying and closing he ticket.
