### ISSUE TITLE
Spock disappeared from the User Guide

### ISSUE THREAD

**Issue by mustaine** [TNG/JGiven#430]
Looks like from the User Guide the Spock section has disappeared
http://jgiven.org/userguide/

Even though looks like is in the index
https://github.com/TNG/JGiven/blob/master/docs/index.adoc

**Comment by janschaefer** [comment]
Yes, strange.

**Comment by janschaefer** [comment]
Fixed. The Spock documentation was not on the release-0.x branch, where I create the documentation from.
