### ISSUE TITLE
Code Formatter improvements

### ISSUE THREAD

**Issue by mustaine** [TNG/JGiven#432]
Would it be useful to open a PR with code formatter standards to review and discuss how to improve the current one https://github.com/TNG/JGiven/blob/master/develop/eclipse-formatter.xml ?

There are some formatting as spaces after parenthesis that might be a bit annoying.

**Comment by janschaefer** [comment]
Yes, I know, however, changing it now would meant to reformat the whole code or would cause a lot of formatting changes. I would like to avoid that.
