### ISSUE TITLE
mvn install failed for 1.0.0-RC3

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#444]
[ERROR] Failed to execute goal com.tngtech.jgiven:jgiven-maven-plugin:1.0.0-RC3:report (default) on project formatXml: Execution default of goal com.tngtech.jgiven:jgiven-maven-plugin:1.0.0-RC3:report failed: A required **class was missing** while executing com.tngtech.jgiven:jgiven-maven-plugin:1.0.0-RC3:report: **com/google/common/collect/Lists**

no problems using 0.18.2

**Comment by janschaefer** [comment]
Yes, this is a known problem. See #441

**Comment by janschaefer** [comment]
Should be fixed with v1.0.0-RC4 now
