### ISSUE TITLE
Presenting PDF attachments

### ISSUE THREAD

**Issue by keesvandieren** [TNG/JGiven#475]
We have business processes that we are testing, which generates PDF documents.

We would like to access those PDF files from test reports.

We've created an attachment as described [here](http://jgiven.org/userguide/#_adding_attachments_to_steps) but it is not yet appearing in the report.

It looks like presenters don't know how to show it in the report? As documented in Attachment class:

    In addition, attachments must have a media type so that reporters know how to present an attachment.

It would be nice if it could be presented as a link, which, on click, opens the PDF.

**Comment by l-1squared** [comment]
Hi @keesvandieren,
normally, attachments should appear as a tiny paper clip in the report. This should be the link you desire. If that is not the case, could you provide me with an example where you attach a pdf, so that I can investigate this more easily?

**Comment by l-1squared** [comment]
Checked your report. If you want to add a pdf, this is easily possible by doing 
```
Attachment pdf = Attachment.fromBinaryFile(new File(pdfPath), MimeType.application("pdf"));
currentStep.addAttachment(pdf);
```
Closing this issue

**Comment by keesvandieren** [comment]
Hi, I did some testing 2 weeks ago in our big JGiven project, the clip was not appearing as of then. I will try again next week. If I still don't see the clip, will reproduce it in a small project, and share the zip if it is still not working then.

**Comment by keesvandieren** [comment]
Verified, it works now. Not sure what is the difference; we upgraded from
0.18.2 to 1.0.0-RC5. Also the way I created the attachment may be different.

Thank you for your explanation.

>

**Comment by l-1squared** [comment]
Great to hear that.
One note on the RC5 release though. We have not pushed that to the gradle plugin repository, due to some error in the publish plugin. We intend to rectify that soon-ish, with a new release.

**Comment by keesvandieren** [comment]
Thanks for notification, we're using Maven so for us the Gradle plugin isn't needed.
