### ISSUE TITLE
special characters in DataProvider

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#497]
In order to test against several CharSet my test data should contain characters like € (Euro Sign).
I was not able to put it in, Using '€' I got x80, Using &#x20AC; I got just this character sequence, but not the Euro Sign.

Should it work?
Or is DataProvider restricted to 7-bit ASCII?

**Comment by l-1squared** [comment]
@rolfschumacher,
sorry for the late reply, I had a very busy schedule the last week. 

Before I come to answer your question, I would kindly ask you to give a little more details as to where you atempted to enter special characters like the '€' sign. This would help me a great deal in attempting to reproduce the issue.

**Comment by l-1squared** [comment]
Dear @rolfschumacher 
I ran the following class as test:
`@ExtendWith( JGivenExtension.class )
@JGivenConfiguration( JGivenTestConfiguration.class )
public class JUnit5Test {

    @ScenarioStage
    GivenStage givenStage;

    @ScenarioStage
    WhenStage whenStage;

    @ScenarioStage
    ThenStage thenStage;

    @ParameterizedTest
    @Tag( "JUnit5 Tag" )
    @ValueSource(strings = {"¼", "25¢", "230€", "Hello JUnit"})
    public void scenario_with_JUnit5(String value) {
        givenStage.given().message( value );
        whenStage.when().handle_message();
        thenStage.then().the_result_is( value + " 5!");
    }
}`
In both the HTML5 and the text report, the special characters showed up just fine. Could you please give a precise example (including JGiven version), where your tests failed to produce the correct characters?

**Comment by l-1squared** [comment]
closed issue, since I did not get a response.
