### ISSUE TITLE
Problems with order of ExtendsWith-Arguments in SpringScenarios

### ISSUE THREAD

**Issue by fudler** [TNG/JGiven#499]
SpringScenarioTests with JUnit5 depend on ordering of arguments of @ExtendWith-Annotation (compare Bug #494).

**Comment by catchin** [comment]
Isn't this fixed with #494 ? Or is something missing?

**Comment by fudler** [comment]
Basically yes, however, we noticed that it is relevant in which order we use the extension; i.e., @ExtendWith({JGivenExtension.class, SpringExtension.class}) yields another result as @ExtendWith({SpringExtension.class, JGivenExtension.class}). We want to understand this behaviour and avoid potential future problems arising from this.

**Comment by catchin** [comment]
According to the [documentation](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-declarative):

> Extension Registration Order
> 
> Extensions registered declaratively via @ExtendWith will be executed in the order in which they are declared in the source code. For example, the execution of tests in both MyFirstTests and MySecondTests will be extended by the DatabaseExtension and WebServerExtension, in exactly that order.

**Comment by l-1squared** [comment]
@catchin my current understanding that the execution order, while fixed should not matter. (This would need to be clarified) So this story is about wether we can find a way to make the execution order irrelevant.

**Comment by l-1squared** [comment]
closed. Effectively works and it is not important enough to investigate further
