### ISSUE TITLE
Allow for commenting of steps

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#50]
It is already possible to provide an extended description to steps by using the `@ExtendedDescription` annotation. However, sometimes you want to comment a certain step-invocation and not all invocations of that step. This comment should also appear in the report.

Example:
```
given().something();
when().some_step()
  .and().some_surprising_step()
   .comment("a comment is especially important here because the step surprises the reader")
  then().something();
```

**Comment by Airblader** [comment]
Just to clarify, this should be really a new piece of information on a step rather than just setting the extendedDescription of a particular step instance?

**Comment by Airblader** [comment]
Also, from my understanding of the codebase, this would roughly involve the following:

* Add a new `comment` property to `Word.java` and add it to the JSON protocol.
* Introduce a new `comment` method in `StageBase.java` (or `Stage.java` to make it language-aware).
 * Introduce a new annotation for such a method, similar to `@IntroWord`.
 * Handle this annotation in `stepMethodInvoked#stepMethodInvoked` by setting the `comment` property of `currentStep` to the argument of the called method (TODO: can we somehow enforce that such a comment method must have exactly one argument of type String?)
* Handle the `comment` property in the HTML reporter (and possibly others?)
 * TODO: how should it be displayed?

I hope I got the basic design of this feature right.
