### ISSUE TITLE
testing services failed

### ISSUE THREAD

**Issue by rolfschumacher** [TNG/JGiven#515]
Java11 Services: Client JGiven test cannot find the providing module.

3 modules: api: ManagerAPI, client: ManagerUI, provider: Manager as maven dependency in ManagerUI pom.xml
The client code in ManagerUI
`::

				List<ManagerAPI> allManagers = ManagerAPI.getInstances();
				if (allManagers.size() < 1) {
					throw new ManagerException("no module found for MangerAPI");
				}
				this.manager = allManagers.get(0);`
fires an exception in the ManagerUITest `static class Steps extends Stage<ManagerUITest.Steps>`, while running it in `static main` finds the provider module.

All modules are installed to local repository using maven.

What may I have overlooked?

**Comment by l-1squared** [comment]
Hi rolf,
I and @fudler  are already lost at parsing your request. Could you please provide more context or a minimal example? For instance, we are already uncertain to what JGiven is the Client and what it has to do with ManagerUI.

**Comment by l-1squared** [comment]
closed, as no clarification was provided
