### ISSUE TITLE
Renovate noise

### ISSUE THREAD

**Issue by jsalinaspolo** [TNG/JGiven#558]
Can we do something with the renovate bot noise? Otherwise, we are gonna get people unwatching the repository

**Comment by l-1squared** [comment]
maybe I should not have activated that just before the holidays :) But you are right. I'll go check

**Comment by l-1squared** [comment]
Bad news, notifications in github seem to based entirely on a pull principle, which seems to be user agnostic. However, you as a user can apparently block messages from individual users: https://webapps.stackexchange.com/questions/119494/disable-notifications-from-github-bots.

The only thing I can really do on the repository is altering the webhooks, in particular to gitter. But again, those are user-agnostic. Also, I don't think that those are the notifications that were bothering you

**Comment by l-1squared** [comment]
I'll go check if I can configure the renovate bot in any way such that it produces less noise. I am not too optimistic though...

**Comment by l-1squared** [comment]
we also need automerges

**Comment by l-1squared** [comment]
automerges have been implemented for minor patches. Noise seems to have been reduced significantly
