### ISSUE TITLE
Documentation not displaying snippets because of error "Unresolved directive in..."

### ISSUE THREAD

**Issue by TobyCourtis** [TNG/JGiven#609]
When opening the documentation for jgiven lots of snippets are not diplayed and show instead the following error:

![Screenshot 2021-03-10 at 15 46 31](https://user-images.githubusercontent.com/24317365/110656368-cb047f80-81b7-11eb-9ac1-16ebe28e5e49.png)

The following sections have this issue:
3.1 https://jgiven.org/userguide/#_create_a_junit_test_class
3.2 https://jgiven.org/userguide/#_create_given_when_and_then_classes
3.3 https://jgiven.org/userguide/#_write_your_first_scenario
3.5 https://jgiven.org/userguide/#_using_junit_rules_directly_instead_of_deriving_from_scenariotest
5.1 https://jgiven.org/userguide/#_step_methods
5.2 https://jgiven.org/userguide/#_overriding_the_default_reporting
5.3 https://jgiven.org/userguide/#_completely_hide_steps
5.3.1 https://jgiven.org/userguide/#_method_parameters
5.4 https://jgiven.org/userguide/#_extended_descriptions
5.6 https://jgiven.org/userguide/#_filler_words
5.7 https://jgiven.org/userguide/#_state_sharing
5.8.1 https://jgiven.org/userguide/#_stage_injection
5.8.2 https://jgiven.org/userguide/#_dynamic_adding_of_stages
5.9 https://jgiven.org/userguide/#_subclassing_of_stages
6.2.1 https://jgiven.org/userguide/#_beforescenario
6.2.2 https://jgiven.org/userguide/#_afterscenario
6.3.1 https://jgiven.org/userguide/#_example_3
6.4.3 https://jgiven.org/userguide/#_example_4
9 https://jgiven.org/userguide/#_tags
9.1 https://jgiven.org/userguide/#_descriptions
9.3 https://jgiven.org/userguide/#_values

**Comment by l-1squared** [comment]
@l-1squared  thanks for the input. I will fix the issue as soon as possible

**Comment by l-1squared** [comment]
fixed by recompiling the documentation

**Comment by l-1squared** [comment]
fixed by recompiling the documentation

**Comment by l-1squared** [comment]
also @TobyCourtis thanks again for taking the time to find all the places where the issue occurred
