### ISSUE TITLE
test logs are visible on class level - no in method level

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#616]
I use Intellij to run tests. 
 When I run tests for a test class then intellij presents it in the following form:

![image](https://user-images.githubusercontent.com/38096038/112439735-c6100600-8d49-11eb-909c-3d22b42ef832.png)

But when I select a single test from the class the log is empty (I expected steps from a single test):
![image](https://user-images.githubusercontent.com/38096038/112439806-d922d600-8d49-11eb-9aed-be31da0a3aa5.png)

It may be caused by the behaviur og jGiven that the Given-When-Then steps are plrinted to the log only after all tests are executed. Is it possible to change this behaviour and log scenarios as they are executed?

It may also help to integrate test reports with other external tools.

**Comment by l-1squared** [comment]
Dear @nnar1o,
you guessed correctly. The test information is added to the report model class, which is only finalized after all tests in that class have run. 

While the idea to publish intermediate text reports is interesting, I expect considerable effort to alter the feature in a way you propose. Also, please keep in mind that test failures are published at the method level, i.e. if a test fails you can read about the error in the method where it ocurred.

Please correct me if I am wrong, but that would mean that the benefit of this huge change would be such that developer can read the test a little more nicely. But a developer can read code. So such a feature would not be essential to him

**Comment by l-1squared** [comment]
Closed, because the amount of effort would be inappropriate for the amount of value generated
