### ISSUE TITLE
Abstract steps of stages should be printed in the report

### ISSUE THREAD

**Issue by petega** [TNG/JGiven#62]
If I define my test specs in a super class with an abstract stage (in the example it is 'given'), and then in the concrete subclass I supply the concrete stage, I would expect a correct report from my test spec. However all abstract stage methods are skipped because they are synthetic.

An example would be the following:

AbstractGiven.java
----------------
    package com.tngtech.jgiven.playground;
    
    import com.tngtech.jgiven.Stage;
    
    public abstract class AbstractGiven<SELF extends AbstractGiven<SELF>> extends Stage<SELF> {
        public abstract SELF I_can_only_be_supplied_by_a_subclass();
    }

SomeTestBase.java
----------------
    package com.tngtech.jgiven.playground;
    
    import com.tngtech.jgiven.Stage;
    import com.tngtech.jgiven.junit.ScenarioTest;
    import org.junit.Test;
    
    public abstract class SomeTestBase<GIVEN extends AbstractGiven<GIVEN>>
        extends ScenarioTest<GIVEN, SomeTestBase.When, SomeTestBase.Then> {

    @Test
    public void I_am_specified_abstractly() {
        given().I_can_only_be_supplied_by_a_subclass();

        when().I_run_a_jgiven_test_with_an_abstract_given_stage();

        then().I_expect_the_abstract_given_step_to_be_printed_in_the_report();
    }

    public static class When extends Stage<When> {
        public When I_run_a_jgiven_test_with_an_abstract_given_stage() {
            return self();
        }
    }

    public static class Then extends Stage<Then> {
        public Then I_expect_the_abstract_given_step_to_be_printed_in_the_report() {
            return self();
        }
    }
}

SyntheticReportTest.java
----------------
    package com.tngtech.jgiven.playground;
    
    public class SyntheticReportTest extends SomeTestBase<SyntheticReportTest.ConcreteGiven> {
    
        public static class ConcreteGiven extends AbstractGiven<ConcreteGiven> {
            @Override
            public ConcreteGiven I_can_only_be_supplied_by_a_subclass() {
                return self();
            }
        }
    }

In the output I would expect a line

    given I can only be supplied by a subclass

however the report looks just like 

    Scenario: I am specified abstractly
    
    When I run the jgiven test with an abstract stage
    Then I expect the abstract given step to be printed in the report

**Comment by janschaefer** [comment]
Interesting. I will have look.

**Comment by janschaefer** [comment]
The issue is fixed now and the methods will appear in the report, however, annotations like `@ExtendedDescription` are currently not detected correctly. The problem is that Java does not copy annotations from the original method to the generated bridge method. The solution to this problem is to find the original method and take the annotations from there.
