### ISSUE TITLE
document usage of attachments

### ISSUE THREAD

**Issue by CrystalMethod** [TNG/JGiven#73]
Please document the usage of attachments. 

I would like to "link" a XML/JSON document from within a certain GIVEN step. This sounds much like an attachment. Will attachments also be linked in HTML reports?

**Comment by janschaefer** [comment]
You can see an example for attachments in the JGiven HTML report: http://jgiven.org/jgiven-report/html5/#/tag/Feature/Attachments so yes, they are linked HTML reports. Documentation is still missing for that, in the meantime you might have a look at some examples and the JavaDoc:

* https://github.com/TNG/JGiven/blob/master/jgiven-tests/src/test/java/com/tngtech/jgiven/report/html5/Html5ReportStage.java
* http://jgiven.org/javadoc/com/tngtech/jgiven/attachment/Attachment.html
* http://jgiven.org/javadoc/com/tngtech/jgiven/CurrentStep.html

The basic usage is to inject the `CurrentStep` class into your stage and call `addAttachment` on it in your step method.

**Comment by CrystalMethod** [comment]
Thx, work as expected - support for ``text/xml``  (or ``application/xml``) would be nice.

**Comment by janschaefer** [comment]
Actually, arbitrary media types are supported. There are only no predefined constants for them. For example, to create a `text/xml` media type you can write:

```
MediaType xml = MediaType.text("xml");
Attachment xmlAttachment = Attachment.fromText("<hello>World</hello>", xml);
```

**Comment by janschaefer** [comment]
I finally managed to write the missing documentation. Please have a [look](http://jgiven.org/docs/attachments/)

**Comment by CrystalMethod** [comment]
Thanks for the hint.
