### ISSUE TITLE
HTML5 Report: Use webjars instead of bower for building

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#75]
Currently bower (and npm) is required for building the HTML5 reporter. Using webjars would remove that dependency.

**Comment by janschaefer** [comment]
It might be better instead to switch to browserify. Than only npm is needed and the HTML5 App can be better unit-tested.

**Comment by wolfs** [comment]
I do not see why you cannot have npm install bower and then call it. Or even use something like grunt or gulp (called and installed by npm). I also do not think that browserify will solve the problem at hand.

**Comment by janschaefer** [comment]
The advantage of browserify would be the easier headless testing.

**Comment by janschaefer** [comment]
Will not be done.
