### ISSUE TITLE
expected exceptions

### ISSUE THREAD

**Issue by CrystalMethod** [TNG/JGiven#76]
I wrote a JGiven/JUnit test with a given expected exception as follows:

```java
@Test(expected="...")
public void test() {
    given().foo();
    when().an_expected_exception_will_be_thrown();
}
```
But the test fails in when()-stage. Is there any chance to use expected exception?

**Comment by CrystalMethod** [comment]
I managed to catch the exception in when() and pass it to then() via @ProvidedScenarioState.

**Comment by janschaefer** [comment]
No. You cannot use that JUnit feature. There is also no direct replacement in JGiven at the moment. Instead what will happen is that JGiven will catch the exception continue executing the scenario where all following steps are just marked as skipped and will throw the caught exception at the end again. However, that is than outside of the actually test method, thus the `expected` thing does not work again.

What you can do is using the `ExpectedException` rule instead:

```
    @Rule
    public ExpectedException rule = ExpectedException.none();

    public void test() {
       rule.expect(MyExpectedException.class);
       given().foo();
       when().an_expected_exception_will_be_thrown();
   }
```

However, typically what you want to do is to check for the exception in the Then stage. So what we typically do is the following:

When-Stage:
```
@ProvidedScenarioState
MyExpectedException someExpectedException;

public SELF an_expected_exception_will_be_thrown() {
   try {
       ...
   } catch (MyExpectedException e) {
      someExpectedException = e;
   }
   return self();
}
```

ThenStage:
```
   @ExpectedScenarioState
   MyExpectedException someExpectedException;

   public SELF the_exception_has_been_thrown() {
       assertThat( someExpectedException ).isNotNull();
   }
```

**Comment by CrystalMethod** [comment]
Thanks for the detailed documentation.

**Comment by nobeh** [comment]
I think it's worth it to include this as part of official documentation.

**Comment by janschaefer** [comment]
I agree

**Comment by janschaefer** [comment]
Done: http://jgiven.org/docs/exceptions/

**Comment by nobeh** [comment]
:+1:

**Comment by albertofaci** [comment]
I just noticed that if the exception is caught by the rule, the test passes but it's shown as failed in the reports

**Comment by janschaefer** [comment]
True, I will update the documentation.
