### ISSUE TITLE
durationInNanos for steps is incorrect

### ISSUE THREAD

**Issue by jasperroelofsen** [TNG/JGiven#761]
When you debug a test you will see that it will set the durationInNanos for a step first to the correct value (ScenarioModelBuilder.stepMethodFinished).
But the step is not changed for things like when, then, and etc.
So when any these complete (which is usually really fast) after the step they will overwrite the actual durationInNanos of the step.

Would be nice if it could keep the value of the step.

**Comment by jasperroelofsen** [comment]
@l-1squared, 
Saw now that this is the same issue as:
https://github.com/TNG/JGiven/issues/755

**Comment by l-1squared** [comment]
Thanks for the bookkeeping :)
