### ISSUE TITLE
Trigger release `1.2.0`

### ISSUE THREAD

**Issue by jsalinaspolo** [TNG/JGiven#790]
Should we release `1.2.0` ? @l-1squared

**Comment by l-1squared** [comment]
Hi,
sorry for not communicating over the holidays. 
I am strongly in favor of doing so, the reason I did not, is that I am currently trying to improve the automation of the release process and I want to see it working in the 1.2.0 release.

**Comment by jsalinaspolo** [comment]
@l-1squared can we trigger a release earlier? 🙏  
We are looking for upgrade to jdk17 and we need the `spock-2.0` module. If automation is not ready, we can make a patch version later on with any dependency update using the automation?

**Comment by l-1squared** [comment]
I attempted a release this moring, but something went awry because my github token was not valid for some reason

**Comment by l-1squared** [comment]
Open points:
- release script is not transactional
- script to publish release on github does not have an execution permission

**Comment by jsalinaspolo** [comment]
Upgraded to spock2, groovy3 and jgiven-spock2. We have been able to upgrade jdk17 ❤️
