### ISSUE TITLE
[Q] @AfterStage in SimpleScenarioTest/Stage

### ISSUE THREAD

**Issue by CrystalMethod** [TNG/JGiven#84]
When using SimpleScenarioTest how do I finish a builder? ``@AfterStage`` is called only once right after all given(), when(), then().

```java
   @AfterStage
   public void buildCustomer() {
       if (customerBuilder != null) {
           customer = customerBuilder.build();
       }
   }
```

**Comment by janschaefer** [comment]
Hi, @AfterStage methods are called directly before the next stage is executed. Thus your example should work actually. Maybe you mean @AfterScenario methods? These are called after the whole scenario has finished.

**Comment by CrystalMethod** [comment]
In this test ``afterStage()`` is called at the end of the scenario, after ``then`` stage.

```java
public class AfterStageTest extends SimpleScenarioTest<AfterStageTestStep> {

    @Test
    public void should_call_afterstage() {
        given().a_given();

        when().a_when();

        then().a_then();
    }

    static class AfterStageTestStep extends Stage<AfterStageTestStep> {

        @AfterStage
        public void afterStage() {
            // builder.build()...
        }

        public AfterStageTestStep a_given() {
            return self();
        }

        public AfterStageTestStep a_when() {
            return self();
        }

        public AfterStageTestStep a_then() {
            return self();
        }

    }

}
```

**Comment by CrystalMethod** [comment]
Currently I use a method annotated with ``@Hidden`` to explicitely finish builders at the end of ``given`` stage.

**Comment by janschaefer** [comment]
Ok. I see. The reason is that you only have a single stage here that you use for all steps. In this case the AfterStage method is indeed only called at the end of the scenario.
