### ISSUE TITLE
Using Hierarchical Tags in 1.2.0 is broken when generating html report

### ISSUE THREAD

**Issue by jadhindieh** [TNG/JGiven#868]
I tried creating Hierarchical tags in jgiven 1.2.0 and the html report never opens. using a single tag in the 1.2.0 we do get an html report.

To reproduce:
- create a parent tag
- create a child tag and annotate it with parent
- add the child annotation to the test case
- generate the html report
- check the results

I have tested this scenario on 0.17.1 and I was able to get an html report, but when I upgrade to 1.2.0, I lose the html report. 
please find attached the screenshots of scenario and results:

- jgiven version:
<img width="328" alt="Screenshot 2022-04-06 at 11 44 12" src="https://user-images.githubusercontent.com/62177543/161949394-17709b7e-74b2-450f-b113-67cfdbad45d5.png">

- tags:
<img width="315" alt="Screenshot 2022-04-06 at 11 44 26" src="https://user-images.githubusercontent.com/62177543/161949475-74e6b83e-e357-4ae3-aa07-ad7eae34aea3.png">
<img width="296" alt="Screenshot 2022-04-06 at 11 44 32" src="https://user-images.githubusercontent.com/62177543/161949509-a08ca1c4-c3c9-4e26-8e65-18ca1584e439.png">

- html tags results:
<img width="309" alt="Screenshot 2022-04-06 at 11 43 58" src="https://user-images.githubusercontent.com/62177543/161949522-2caea89c-1f45-4cb8-bac0-a8b65a14757b.png">

- jgiven version:
<img width="370" alt="Screenshot 2022-04-06 at 11 51 02" src="https://user-images.githubusercontent.com/62177543/161949690-7b5d47a5-aa38-46a3-b27b-7a4b9ab6b0c4.png">

- no change to code

- html tags results:
<img width="1338" alt="Screenshot 2022-04-06 at 11 50 40" src="https://user-images.githubusercontent.com/62177543/161949756-060f3120-c960-4e62-bd00-97592467b1ed.png">

**Comment by l-1squared** [comment]
Hi,
thanks for informing me about the issue. I will attempt to solve the issue  as soon as possible (probably monday)

**Comment by l-1squared** [comment]
Managed to reproduce the bug. Feature still seems to work with version 1.1.0

**Comment by l-1squared** [comment]
apparently the issue occurs with this commit: fd978254a2494e8dde4bc194ea42251647c8fef2. It appears that the parent tags do not get written into the tagMap.js anymore.
Will continue investigation tomorrow

**Comment by jadhindieh** [comment]
Thank you for the fast resolution

**Comment by l-1squared** [comment]
@jadhindieh  Thanks for reporting. I have an idea how that came to pass.

**Comment by l-1squared** [comment]
@jadhindieh I think I found the cause, but I want to take some more time to consolidate the code and maybe come up with another test or two.
