### ISSUE TITLE
Hierarchy for Tags or Tests

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#90]
To advocate for JGiven in a larger project I would like to see hierarchies for test cases. 

This could lead to a business motivated hierarchy like: 

    category1\subcategory1\usecase1
    category1\subcategory1\usecase2
    category1\subcategory2\usecase3
    category2\subcategory3\usecase4
    category2\subcategory3\usecase5

One source of a hierarchy could be java package names (in JGiven i.e. see all tests in the com.tngtech.jgiven.report package). But this allows only for one hierarchy in the project. 

Another source could a category for tags. Some pseudo-code:

    @IsTag( type = "Usecase", value = "Usecase 1",
        description = "...", category = { "category1", "subcategory1" } )
    @Retention( RetentionPolicy.RUNTIME )
    public @interface Usecase1 {
    
    }

As we have a `TagDescriptionGenerator` it would be useful for me to have also a `TagCategoryGenerator` to allow for parameterized annotations like this

    @Usecase(name = "Usecase1", category = { "category1", "subcategory1" })

Please comment if you find this useful as well.

Thanks!

**Comment by janschaefer** [comment]
This is more or less the same as #27 regarding the tags.
Regarding the hierarchy of test classes, do you mean that in the HTML5 report the test classes should be hierarchically structured by package name. Something like:
```
com
  tngtech
      jgiven
         report
         impl
         ...
```
Maybe even having the possibility to show all scenarios of a certain package?

**Comment by janschaefer** [comment]
In #27 the suggestion would be to be define categories again as Java annotations and then annotate the `@IsTag` annotation with these categories, e.g.:

```
@Category1
@SubCategory2
@IsTag( type = "Usecase", value = "Usecase 1",
    description = "..."
@Retention( RetentionPolicy.RUNTIME )
public @interface Usecase1 {
}
```

**Comment by ahus1** [comment]
@janschaefer - regarding package names, yes, a layout like

    com
      tngtech
          jgiven
             report
             impl
             ...

would be perfect. When I select a package I would like to see the test cases in the selected package **and in the subpackages**.

**Comment by ahus1** [comment]
@janschaefer - regarding annotations as outlined in #27 it would work for me as long as I can define as many hierarchy levels as needed. I the order of the annotations preserved (1st annotation = 1st level, 2nd annotation = 2nd level)?

BTW: I didn't think that #27 named "Meta Tag" would contain such a nice thing ... :-)

**Comment by janschaefer** [comment]
Well, I actually would rather say that you only put the subcategory annotation to the tag. And the subcategory has as annotation the category, something like:

```
@SubCategory2
@IsTag( type = "Usecase", value = "Usecase 1",
    description = "..."
@Retention( RetentionPolicy.RUNTIME )
public @interface Usecase1 {
}
```

```
@Category1
@IsTag( type = "Usecase", value = "Usecase 1",
    description = "..."
@Retention( RetentionPolicy.RUNTIME )
public @interface SubCategory2 {
}
```

**Comment by ahus1** [comment]
ok for me as long as multiple category levels are possible in the report.

**Comment by janschaefer** [comment]
Sure. Ok, I will try to implement that. Shouldn't be too hard ;-)

**Comment by janschaefer** [comment]
Hierarchy for test class is now implemented in PR #91

**Comment by ahus1** [comment]
Just built current version locally to have a look at PR #91. Looks really nice! Thanks a lot!

**Comment by janschaefer** [comment]
Ok. Cool :-). Regarding the hierarchical tags: I am working on it, but it turned out to be more difficult than I first expected. I am nearly done though.

**Comment by janschaefer** [comment]
Finally the feature is now implemented. #99

**Comment by ahus1** [comment]
Just looked at the jgiven-tests built from trunk. Tree navigation for features and classes is amazing. Thanks, Jan!

![treenav_jgiven](https://cloud.githubusercontent.com/assets/3957921/9047948/afa597da-3a35-11e5-9ad6-37e092202961.PNG)

**Comment by janschaefer** [comment]
Thx :-)
